In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_290_16 = snp_anal.series_anal_cls(dm.di_290_16, sm.series_data)

<h3>Series 290_16</h3>
<div style="width:700px">
<p>
This notebook documents the series 290_16 and its 290 SNPs. The 1000 genomes data include
include 4970 chromosome 2 samples that express none of these 290 SNPs and 16 that express all
290 of them.  All 16 samples express all 117 117_1685 SNPs.  14 of the samples express a specific
96 SNP fragment of 123_1561.  The other 2 have each lost one of those SNPs.  All 16 samples
express a specific 40 SNP fragment of 62_1265.  None of the 16 samples express any of the
193 SNPs in the series 193_843.
</div>

In [2]:
HTML(dm.series_html(dm.di_290_16))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_290_16], min_match=0.9)
plt = plt_obj.do_plot()
show(plt)

In [4]:
am_290_16 = an.lct_obj.yes_no_data_indexes([dm.di_290_16])

In [5]:
count_data = sa_290_16.unique_snps_per_allele()
count_data

array([(0, 4970), (1, 20), (2, 1), (16, 1), (290, 16)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
count_data = an.sa_117_1685.unique_snps_per_allele(am_290_16)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(117, 16)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
count_data = an.sa_123_1561.unique_snps_per_allele(am_290_16)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [9]:
count_data

array([(95, 2), (96, 14)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
an.sa_123_1561.alleles_per_snp(am_290_16)

array([16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16,  0,  0,  0, 16,  0,  0, 16, 16, 16, 16,  0, 16,  0,
        0,  0,  0, 16,  0, 16,  0,  0,  0,  0, 16,  0, 16, 16,  0, 16,  0,
        0, 16, 16, 16, 16, 16, 16, 16,  0,  0, 15,  0,  0, 16,  0, 16, 16,
       16, 16,  0, 16,  0,  0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16])

In [11]:
count_data = an.sa_62_1265.unique_snps_per_allele(am_290_16)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [12]:
count_data

array([(40, 16)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [13]:
an.sa_62_1265.alleles_per_snp(am_290_16)

array([16, 16, 16,  0,  0, 16, 16,  0,  0,  0, 16, 16,  0, 16, 16, 16,  0,
       16, 16, 16,  0, 16, 16, 16, 16, 16, 16, 16,  0,  0, 16, 16, 16, 16,
       16, 16,  0, 16,  0,  0,  0, 16, 16, 16, 16,  0,  0, 16,  0, 16,  0,
       16,  0,  0,  0, 16, 16,  0, 16, 16, 16, 16])

In [14]:
count_data = an.sa_193_843.unique_snps_per_allele(am_290_16)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [15]:
count_data

array([(0, 16)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [16]:
plt_obj = dm.superset_yes_no([dm.di_290_16, dm.di_39_1014], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
an.sa_123_1561.alleles_per_snp(am)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  9, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10,  0,  0,  0, 10,  0,  0, 10, 10, 10, 10,  0, 10,  0,
        0,  0,  0, 10,  0, 10,  0,  0,  0,  0, 10,  0, 10, 10,  0, 10,  0,
        0, 10, 10, 10, 10, 10, 10, 10,  0,  0,  9,  0,  0, 10,  0, 10, 10,
       10, 10,  0, 10,  0,  0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10])

In [19]:
plt_obj = dm.superset_yes_no([dm.di_290_16, dm.di_24_1504], [dm.di_39_1014], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
an.sa_123_1561.alleles_per_snp(am)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 4, 0, 0, 4, 4,
       4, 4, 0, 4, 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 4, 0, 4, 4, 0, 4, 0, 0,
       4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 0, 0, 4, 0, 4, 4, 4, 4, 0, 4, 0, 0, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4])

In [22]:
plt_obj = dm.superset_yes_no([dm.di_290_16, dm.di_64_1575], [dm.di_24_1504, dm.di_39_1014], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
an.sa_123_1561.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
plt_obj = dm.superset_yes_no([dm.di_290_16], [dm.di_64_1575, dm.di_24_1504, dm.di_39_1014], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [26]:
HTML(plt_obj.get_html())

In [27]:
an.sa_123_1561.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])