In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_22_73 = snp_anal.series_anal_cls(dm.di_22_73, sm.series_data)
am_22_73 = dm.allele_mask_from_index(dm.di_22_73)

<h3>Series 22_73</h3>
<div style="width:700px">
<p>
This notebook documents the series 22_73 and its 22 SNPs. The 1000 genomes data include
include 4922 chromosome 2 samples that express none of these 22 SNPs, 70 that express all
22 of them and 3 that express 21 of them.
<p>
The series 22_73 has selected the 28_434 hierarchy that expresses 13_1696 and 117_1685 but
not 123_1561.  Its history started with a chromosome that expressed 117_1685, 9_887, 8_718,
5_588, 9_545, 28_434, 70_166, and 49_136.  That chromosome recombined with one that expressed
13_1696.  The result of the event was a chromosome that expressed 13_1696 in addition to all
of the other series.  The first 10 SNPs of 117_1685 were lost in the recombination event.  The
SNPs selected by the emergence of 22_73 also lost one more 117_1685 SNP from the middle of the series.
But, enough 117_1685 SNPs were retained for it to meet the threshold to be counted as an expressed
series.
<p>
All 73 chromosome samples that express 22_73 also express fragments of 123_1561 that range
from 107 through 110 SNPs.  The samples also express fragments of 62_1265 that range from 2 through 5
SNPs and a 2 SNP fragment of 193_843.
</div>

In [2]:
HTML(dm.series_html(dm.di_22_73))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_22_73], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
count_data = sa_22_73.unique_snps_per_allele()
count_data

array([(0, 4922), (1, 10), (4, 1), (18, 1), (19, 1), (21, 3), (22, 70)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
count_data = an.sa_13_1696.unique_snps_per_allele(am_22_73)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(12, 11), (13, 62)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
count_data = sa_117_1685.unique_snps_per_allele(am_22_73)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [9]:
count_data

array([(105, 3), (106, 68), (107, 2)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
an.sa_117_1685.alleles_per_snp(am_22_73)

array([ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 70, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73,  1, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73])

In [11]:
aps_106, am_106 = an.sa_117_1685.snps_from_aps_value(106, am_22_73)
aps_106

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68,  0, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68])

In [12]:
count_data = sa_123_1561.unique_snps_per_allele(am_22_73)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [13]:
count_data

array([(107, 8), (108, 50), (109, 14), (110, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [14]:
an.sa_123_1561.alleles_per_snp(am_22_73)

array([73, 73, 73, 73,  0, 14,  0, 73, 73,  1,  1, 73, 73, 73,  0,  1,  0,
        0, 73, 72,  0, 73, 73,  0, 73, 73, 73, 73, 73, 73, 73, 73,  0, 72,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73,  0, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 66, 73, 73, 73, 73,  0,
       73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73,  0, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73])

In [15]:
aps_109, am_109 = an.sa_123_1561.snps_from_aps_value(109, am_22_73)
aps_109

array([14, 14, 14, 14,  0, 14,  0, 14, 14,  0,  0, 14, 14, 14,  0,  1,  0,
        0, 14, 14,  0, 14, 14,  0, 14, 14, 14, 14, 14, 14, 14, 14,  0, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14,  0, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 14, 14, 14, 14,  0,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14,  0, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14])

In [16]:
aps_108, am_108 = an.sa_123_1561.snps_from_aps_value(108, am_22_73)
aps_108

array([50, 50, 50, 50,  0,  0,  0, 50, 50,  0,  0, 50, 50, 50,  0,  0,  0,
        0, 50, 50,  0, 50, 50,  0, 50, 50, 50, 50, 50, 50, 50, 50,  0, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50,  0, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,  0,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50,  0, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50])

In [17]:
count_data = sa_62_1265.unique_snps_per_allele(am_22_73)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [18]:
count_data

array([(2, 18), (3, 33), (4, 12), (5, 10)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [19]:
an.sa_62_1265.alleles_per_snp(am_22_73)

array([ 0, 73, 73, 22, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0, 42,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [20]:
aps_5, am_5 = an.sa_62_1265.snps_from_aps_value(5, am_22_73)
aps_5

array([ 0, 10, 10, 10, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [21]:
aps_4, am_4 = an.sa_62_1265.snps_from_aps_value(4, am_22_73)
aps_4

array([ 0, 12, 12, 12, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [22]:
aps_3, am_3 = an.sa_62_1265.snps_from_aps_value(3, am_22_73)
aps_3

array([ 0, 33, 33,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [23]:
aps_2, am_2 = an.sa_62_1265.snps_from_aps_value(2, am_22_73)
aps_2

array([ 0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [24]:
count_data = sa_193_843.unique_snps_per_allele(am_22_73)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [25]:
count_data

array([(2, 72), (3, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
an.sa_193_843.alleles_per_snp(am_22_73)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, 73, 73,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])