In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_209_56 = snp_anal.series_anal_cls(dm.di_209_56, sm.series_data)
am_209_56 = dm.allele_mask_from_index(dm.di_209_56)

<h3>Series 209_56</h3>
<div style="width:700px">
<p>
This notebook documents the series 209_56 and its 209 SNPs. The 1000 genomes data includes 4899
chromosome 2 samples that express none of these 209 SNPs and 48 samples that express all 209 of them.
Another 6 samples express 208 of them.  The series extends over 617,000 DNA bases in the same part
of chromosome 2 as the series 117_1685, 123_1561, 62_1265, and 193_843.  All 56 of the chromosome
samples that express 209_56 also express 117_1685, 123_1561, and 62_1265.
<p>
209_56 is a third case like 193_843 and 67_329 where a long series of a large number of SNPs has
selected an hierarchy that includes the same three other long series of large numbers of SNPs.
The only difference in this case is that the instances of 123_1561 associated with 209_56 are
missing one of the 123_1561 SNPs.
<p>
The series 209_56 is also strongly associated with 26_1414, 10_2206, and 14_48.  The emergence
of 209_56 appears to have marked an independent selection of 26_1414_and 10_2206, two series
that are part of the EUR tree root.  However, the version of 26_1414 associated with 209_56 has
lost 3 of its 26 SNPs.

In [2]:
HTML(dm.series_html(dm.di_209_56))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_209_56], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
count_data = sa_209_56.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [6]:
count_data

array([(0, 4899), (1, 43), (3, 1), (5, 1), (11, 4), (14, 1), (119, 1),
       (120, 1), (186, 1), (189, 1), (192, 1), (208, 6), (209, 48)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
count_data = an.sa_117_1685.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [8]:
count_data

array([(116, 16), (117, 40)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [9]:
count_data = an.sa_123_1561.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [10]:
count_data

array([(121, 7), (122, 49)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [11]:
aps_122, am_122 = an.sa_123_1561.snps_from_aps_value(122, am_209_56)
aps_122

array([49, 49, 49, 49, 49, 49, 49, 49, 49, 49,  0, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49])

In [12]:
aps_121, am_121 = an.sa_123_1561.snps_from_aps_value(121, am_209_56)
aps_121

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 5, 7, 7, 7])

In [13]:
count_data = an.sa_62_1265.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [14]:
count_data

array([(61, 2), (62, 54)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [15]:
count_data = an.sa_193_843.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [16]:
count_data

array([(5, 49), (6, 6), (7, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [17]:
aps_5, am_5 = an.sa_193_843.snps_from_aps_value(5, am_209_56)
aps_5

array([49,  0, 49,  0, 49, 49, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [18]:
count_data = an.sa_26_1414.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [19]:
count_data

array([(0, 4), (17, 1), (23, 50), (26, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [20]:
aps_23, am_23 = an.sa_26_1414.snps_from_aps_value(23, am_209_56)
aps_23

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
        0, 50, 50, 50,  0, 50,  0, 50, 50])

In [21]:
di_14_48 = 353833
sa_14_48 = snp_anal.series_anal_cls(di_14_48, sm.series_data)
am_14_48 = dm.allele_mask_from_index(di_14_48)
count_data = sa_14_48.unique_snps_per_allele(am_209_56)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [22]:
count_data

array([(0, 6), (6, 1), (9, 3), (14, 46)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [23]:
sa_14_48.alleles_per_snp(am_209_56)

array([50, 50, 50, 50, 50, 50, 49, 49, 49, 46, 46, 46, 46, 46])