In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_6_68 = snp_anal.series_anal_cls(dm.di_6_68, sm.series_data)
am_6_68 = dm.allele_mask_from_index(dm.di_6_68)
sa_49_136 = snp_anal.series_anal_cls(dm.di_49_136, sm.series_data)

<h3>Series 6_68</h3>
<div style="width:700px">
<p>
This notebook documents the series 6_68 and its 6 SNPs. The 1000 genomes data includes 4935
chromosome 2 samples that express none of these 6 SNPs, 5 samples that express 1 of them,
7 samples that express 5 of them and 61 samples that express all 6.  The samples that
express 5 are counted as expressing the series.
<p>
6_68 is the series that has selected the part of the 49_136 hierarchy that did not experience
a recombination event with the series 13_1696.  But, 7 of the samples that express 6_68 do
not express 49_136.  One of them does not express 28_434.  Those 7 samples are the same ones
that only express 5 6_68 SNPs.  But, the history is different for the 6 that express 28_434
and the 1 that does not.
<p>
The 6 samples that have lost 49_136 but not 28_434 all have lost the second SNP in the series
6_68.  All of them have also lost the same 7 SNPs from 49_136.  The locations of those SNPs
are dispersed over the 49_136 series.  4 of those samples have lost 1 more 49_136 SNP.
<p>
The sample that does not express 49_136 or 28_434 has undergone a recombination event that
lost the last 6_68 SNP.  The event associated 6_68 with the 67_329 hierarchy that includes
expression of 62_1265, 123_1561, and 117_1685.
</div>

In [2]:
HTML(dm.series_html(dm.di_6_68))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_6_68], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
count_data = sa_6_68.unique_snps_per_allele()
count_data

array([(0, 4935), (1, 5), (5, 7), (6, 61)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
plt_obj = dm.superset_yes_no([dm.di_6_68], [dm.di_49_136, dm.di_123_1561], min_match=0.5)
plt = plt_obj.do_plot()
am_not_49_136_123_1561 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [7]:
HTML(plt_obj.get_html())

In [8]:
count_data = sa_6_68.unique_snps_per_allele(am_not_49_136_123_1561)
count_data

array([(5, 6)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [9]:
sa_6_68.alleles_per_snp(am_not_49_136_123_1561)

array([6, 0, 6, 6, 6, 6])

In [10]:
count_data = sa_49_136.unique_snps_per_allele(am_not_49_136_123_1561)
count_data

array([(40, 4), (41, 2)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [11]:
sa_49_136.alleles_per_snp(am_not_49_136_123_1561)

array([6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 0, 6, 6, 0, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6, 6, 6, 6, 6, 0, 6, 6,
       6, 6, 6])

In [12]:
plt_obj = dm.superset_yes_no([dm.di_6_68, dm.di_123_1561], [dm.di_49_136], min_match=0.5)
plt = plt_obj.do_plot()
am_123_1561_not_49_136 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
count_data = sa_6_68.unique_snps_per_allele(am_123_1561_not_49_136)
count_data

array([(5, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [15]:
sa_6_68.alleles_per_snp(am_123_1561_not_49_136)

array([1, 1, 1, 1, 1, 0])

In [16]:
count_data = sa_49_136.unique_snps_per_allele(am_123_1561_not_49_136)
count_data

array([(0, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [17]:
count_data = sa_117_1685.unique_snps_per_allele(am_6_68)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [18]:
count_data

array([(114, 2), (115, 6), (116, 58), (117, 2)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [19]:
aps_116, am_116 = an.sa_117_1685.snps_from_aps_value(116, am_6_68)
aps_116

array([58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 57, 58, 58, 58, 58, 58, 58, 58, 58, 58, 54, 58, 58, 58,
       58, 58, 58, 58, 58, 58, 58, 58, 58,  5, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58])

In [20]:
count_data = sa_123_1561.unique_snps_per_allele(am_6_68)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [21]:
count_data

array([(106, 1), (107, 3), (108, 2), (109, 44), (110, 17), (123, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
aps_110, am_110 = an.sa_123_1561.snps_from_aps_value(110, am_6_68)
aps_110

array([17, 17, 17, 17,  0, 17,  0, 17, 17,  0,  1, 17, 17, 17,  0, 16,  4,
        0, 17, 17,  0, 17, 17,  0, 17, 17, 17, 17, 17, 17, 17, 17,  0, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  0, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 13, 17, 17, 17, 17,  0,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17])

In [23]:
aps_109, am_109 = an.sa_123_1561.snps_from_aps_value(109, am_6_68)
aps_109

array([44, 44, 44, 44,  0, 44,  0, 44, 44,  0,  0, 44, 44, 44,  0,  0,  0,
        0, 44, 44,  0, 44, 44,  0, 44, 44, 44, 44, 44, 44, 44, 44,  0, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44,  0, 44, 44, 44, 44, 44, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,  0,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
       44, 44, 44,  0, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
       44, 44, 44, 44])

In [24]:
count_data = sa_62_1265.unique_snps_per_allele(am_6_68)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [25]:
count_data

array([(4, 8), (5, 14), (6, 20), (7, 22), (8, 3), (62, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
aps_7, am_7 = an.sa_62_1265.snps_from_aps_value(7, am_6_68)
aps_7

array([22, 22, 22, 21, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 21])

In [27]:
aps_6, am_6 = an.sa_62_1265.snps_from_aps_value(6, am_6_68)
aps_6

array([20, 20, 20, 20, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8])

In [28]:
aps_5, am_5 = an.sa_62_1265.snps_from_aps_value(5, am_6_68)
aps_5

array([14, 14, 14,  5,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9])

In [29]:
count_data = sa_193_843.unique_snps_per_allele(am_6_68)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [30]:
count_data

array([(1, 13), (2, 55)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [31]:
aps_2, am_2 = an.sa_193_843.snps_from_aps_value(2, am_6_68)
aps_2

array([55,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 37,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])