In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)

<h3>Series 62_1265</h3>
<div style="width:700px">
<p>
This notebook documents the series 62_1265 and its 62 SNPs. The 1000 genomes data includes 3234
chromosome 2 samples that express none of these 62 SNPs and 1096 samples that express all of them.
Another 70 that express 61 of them. 
<p>
There are 331 chromosome samples that express  4 or more SNP fragments of series 62_1265.  This
notebook explores the hierarchies associated with some of those fragments
<p>
The fragement expressed by 85 chromosome samples includes only the first 8 62_1265 SNPs.  It resulted
from a recombination event between the South Asian tree and the East Asian tree that associated
the series 4_815 and 5_684.
<p>
Two other hierarchies include fragments of 62_1265.  One is the hierarchy selected by the series
290_16.  The other was selected by the series 219_26.  The 16 chromosome samples that express
290_16 all express a 40 SNP fragement of 62_1265.  The 26 chromosome samples that express
219_26 express either 48 or 47 SNP fragments of 62_1265.
<p>
A significant number of the remaining 62_1265 fragments are part of 28_434 hierarchies.  A number
of those fragments include small numbers of 62_1265 SNPs.
</div>

In [2]:
HTML(dm.series_html(dm.di_62_1265))

In [3]:
count_data = an.sa_62_1265.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [4]:
count_data

array([(0, 3234), (1, 103), (2, 40), (3, 38), (4, 22), (5, 42), (6, 20),
       (7, 26), (8, 95), (9, 4), (20, 18), (21, 6), (22, 9), (23, 4),
       (36, 3), (37, 1), (40, 16), (41, 1), (43, 1), (47, 13), (48, 13),
       (49, 9), (52, 9), (53, 6), (54, 8), (55, 2), (56, 3), (57, 5),
       (58, 9), (59, 36), (60, 46), (61, 70), (62, 1096)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
22+42+20+26+95+4+18+6+9+4+3+1+16+1+1+13+13+9+9+6+8+2+3

331

In [6]:
aps_54, am_54 = an.sa_62_1265.snps_from_aps_value(54)
aps_54

array([5, 5, 5, 5, 5, 5, 5, 5, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
aps_52, am_52 = an.sa_62_1265.snps_from_aps_value(52)
aps_52

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 9, 9, 9, 9, 9, 5, 5, 5, 9, 5, 9, 9, 9, 9,
       5, 9, 9, 9, 9, 9, 9, 5, 5, 5, 9, 5, 5, 9, 9, 9, 9, 4, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [8]:
aps_49, am_49 = an.sa_62_1265.snps_from_aps_value(49)
aps_49

array([0, 0, 0, 0, 0, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 0,
       0, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 0, 9, 9, 9, 9])

In [9]:
aps_48, am_48 = an.sa_62_1265.snps_from_aps_value(48)
aps_48

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13, 13, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [10]:
aps_47, am_47 = an.sa_62_1265.snps_from_aps_value(47)
aps_47

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 12, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13,  1, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [11]:
aps_40, am_40 = an.sa_62_1265.snps_from_aps_value(40)
aps_40

array([16, 16, 16,  0,  0, 16, 16,  0,  0,  0, 16, 16,  0, 16, 16, 16,  0,
       16, 16, 16,  0, 16, 16, 16, 16, 16, 16, 16,  0,  0, 16, 16, 16, 16,
       16, 16,  0, 16,  0,  0,  0, 16, 16, 16, 16,  0,  0, 16,  0, 16,  0,
       16,  0,  0,  0, 16, 16,  0, 16, 16, 16, 16])

In [12]:
aps_22, am_22 = an.sa_62_1265.snps_from_aps_value(22)
aps_22

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 0, 9,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
aps_20, am_20 = an.sa_62_1265.snps_from_aps_value(20)
aps_20

array([18, 18, 18,  0,  0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18,  0, 18, 18,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [14]:
aps_8, am_8 = an.sa_62_1265.snps_from_aps_value(8)
aps_8

array([94, 94, 94, 94, 94, 91, 91, 91,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        3,  0,  0,  0,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0])

In [15]:
aps_7, am_7 = an.sa_62_1265.snps_from_aps_value(7)
aps_7

array([24, 26, 26, 22, 22,  3,  3,  3,  2,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  1,  1,  1, 22])

In [16]:
aps_6, am_6 = an.sa_62_1265.snps_from_aps_value(6)
aps_6

array([20, 20, 20, 20, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8])

In [17]:
aps_5, am_5 = an.sa_62_1265.snps_from_aps_value(5)
aps_5

array([31, 41, 41, 33, 33,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9])

In [18]:
aps_4, am_4 = an.sa_62_1265.snps_from_aps_value(4)
aps_4

array([ 8, 21, 21, 13, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  3])

In [19]:
plt_obj = dm.superset_allele_mask(am_54, [dm.di_32_1361], min_match=0.5)
plt = plt_obj.do_plot()
am_54_32_1361 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
aps_54_32_1361, am_54_32_1361 = an.sa_62_1265.snps_from_aps_value(54, am_54_32_1361)
aps_54_32_1361

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
plt_obj = dm.superset_allele_mask(am_52, [dm.di_13_1696], min_match=0.5)
plt = plt_obj.do_plot()
am_52_13_1696 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
aps_52_13_1696, am_54_13_1696 = an.sa_62_1265.snps_from_aps_value(52, am_52_13_1696)
aps_52_13_1696

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [25]:
plt_obj = dm.superset_allele_mask(am_49, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [26]:
HTML(plt_obj.get_html())

In [27]:
an.sa_62_1265.alleles_per_snp(am_49)

array([0, 0, 0, 0, 0, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 0,
       0, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 0, 9, 9, 9, 9])

In [28]:
plt_obj = dm.superset_allele_mask(am_48, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [29]:
HTML(plt_obj.get_html())

In [30]:
an.sa_62_1265.alleles_per_snp(am_48)

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13, 13, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [31]:
plt_obj = dm.superset_allele_mask(am_47, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [32]:
HTML(plt_obj.get_html())

In [33]:
an.sa_62_1265.alleles_per_snp(am_47)

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 12, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13,  1, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [34]:
plt_obj = dm.superset_allele_mask(am_40, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [35]:
HTML(plt_obj.get_html())

In [36]:
an.sa_62_1265.alleles_per_snp(am_40)

array([16, 16, 16,  0,  0, 16, 16,  0,  0,  0, 16, 16,  0, 16, 16, 16,  0,
       16, 16, 16,  0, 16, 16, 16, 16, 16, 16, 16,  0,  0, 16, 16, 16, 16,
       16, 16,  0, 16,  0,  0,  0, 16, 16, 16, 16,  0,  0, 16,  0, 16,  0,
       16,  0,  0,  0, 16, 16,  0, 16, 16, 16, 16])

In [37]:
plt_obj = dm.superset_allele_mask(am_22, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [38]:
HTML(plt_obj.get_html())

In [39]:
an.sa_62_1265.alleles_per_snp(am_22)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 0, 9,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
plt_obj = dm.superset_allele_mask(am_20, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [41]:
HTML(plt_obj.get_html())

In [42]:
an.sa_62_1265.alleles_per_snp(am_20)

array([18, 18, 18,  0,  0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18,  0, 18, 18,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [43]:
plt_obj = dm.superset_allele_mask(am_8, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [44]:
HTML(plt_obj.get_html())

In [45]:
an.sa_62_1265.alleles_per_snp(am_8)

array([94, 94, 94, 94, 94, 91, 91, 91,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        3,  0,  0,  0,  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0])

In [46]:
plt_obj = dm.superset_allele_mask(am_8, [dm.di_5_684], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [47]:
HTML(plt_obj.get_html())

In [48]:
an.sa_62_1265.alleles_per_snp(am)

array([85, 85, 85, 85, 85, 85, 85, 85,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [49]:
plt_obj = dm.superset_allele_mask(am_5, [dm.di_28_434], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [50]:
HTML(plt_obj.get_html())

In [51]:
an.sa_62_1265.alleles_per_snp(am)

array([15, 25, 25, 16, 16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9])

In [52]:
plt_obj = dm.superset_allele_mask(am_5, [dm.di_7_1760], [dm.di_28_434], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [53]:
HTML(plt_obj.get_html())

In [54]:
an.sa_62_1265.alleles_per_snp(am)

array([8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])