In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_219_26 = snp_anal.series_anal_cls(dm.di_219_26, sm.series_data)
am_219_26 = dm.allele_mask_from_index(dm.di_219_26)

<h3>Series 219_26</h3>
<div style="width:700px">
<p>
This notebook documents the series 219_26 and its 219 SNPs. The 1000 genomes data includes 4956
chromosome 2 samples that express none of these 219 SNPs and 20 samples that express all 219 of them.
The series extends over 702,000 DNA bases in the same part of chromosome 2 as the series 117_1685,
123_1561, 62_1265, and 193_843.  All 26 of the chromosome samples that express 209_56 also express 
123_1561, 9_887, and 22_35.  None of them express 117_1685, 62_1265, or 193_843.
<p>
All 26 samples express all 123 123_1561 SNPs.  All of them also express
significant fragments of 117_1685 and 62_1265.  None of them expresses a significant fragment
of the series 193_843.
<p>
219_26 represents another complex history that has selected 123_1561 along with a very large
number of other SNPs.
</div>

In [2]:
HTML(dm.series_html(dm.di_219_26))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_219_26], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [29]:
count_data = sa_219_26.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [30]:
count_data

array([(0, 4956), (1, 18), (2, 2), (4, 2), (5, 1), (15, 2), (33, 1),
       (205, 1), (216, 2), (217, 1), (218, 2), (219, 20)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
count_data = sa_117_1685.unique_snps_per_allele(am_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [6]:
count_data

array([(43, 22), (44, 1), (46, 1), (47, 1), (53, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
sa_117_1685.alleles_per_snp(am_219_26)

array([ 1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, 26,  3,  0,  3,  0,  0,
        0,  0,  0, 26,  2,  0,  0,  0, 26,  0,  0,  0,  3,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 23,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0, 26, 26, 26, 26, 26,
       26, 26,  0, 26,  1,  1, 26,  0, 25, 26,  0, 26,  0, 26,  1, 26,  0,
       26,  0, 25, 26, 26,  1,  1,  1,  1,  2, 26, 26, 26, 26, 26, 26, 26,
       26,  0, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26])

In [8]:
aps_43, am_43 = an.sa_117_1685.snps_from_aps_value(43, am_219_26)
aps_43

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,
        0,  0,  0, 22,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22,
       22, 22,  0, 22,  0,  0, 22,  0, 22, 22,  0, 22,  0, 22,  0, 22,  0,
       22,  0, 22, 22, 22,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22, 22, 22,
       22,  0, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [9]:
count_data = sa_123_1561.unique_snps_per_allele(am_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [10]:
count_data

array([(123, 26)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [11]:
count_data = sa_62_1265.unique_snps_per_allele(am_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [12]:
count_data

array([(47, 13), (48, 13)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [13]:
sa_62_1265.alleles_per_snp(am_219_26)

array([ 0,  0,  0,  0,  0, 26, 26,  0, 26, 26, 26, 26, 26, 26, 26, 26,  0,
       26, 26, 26, 26, 25, 26, 26, 26, 26, 26, 26, 26,  0, 26, 26, 26, 26,
       26, 26, 26, 26,  0, 26, 14, 26, 26, 26, 26,  0,  0, 26, 26, 26, 26,
       26, 26, 26,  0, 26, 26,  0, 26,  0, 26, 26])

In [14]:
aps_48, am_48 = an.sa_62_1265.snps_from_aps_value(48, am_219_26)
aps_48

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13, 13, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [15]:
aps_47, am_47 = an.sa_62_1265.snps_from_aps_value(47, am_219_26)
aps_47

array([ 0,  0,  0,  0,  0, 13, 13,  0, 13, 13, 13, 13, 13, 13, 13, 13,  0,
       13, 13, 13, 13, 12, 13, 13, 13, 13, 13, 13, 13,  0, 13, 13, 13, 13,
       13, 13, 13, 13,  0, 13,  1, 13, 13, 13, 13,  0,  0, 13, 13, 13, 13,
       13, 13, 13,  0, 13, 13,  0, 13,  0, 13, 13])

In [16]:
count_data = sa_193_843.unique_snps_per_allele(am_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [17]:
count_data

array([(0, 25), (1, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [18]:
aps_43, am_43 = sa_117_1685.snps_from_aps_value(43, am_219_26)
aps_43

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,
        0,  0,  0, 22,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22,
       22, 22,  0, 22,  0,  0, 22,  0, 22, 22,  0, 22,  0, 22,  0, 22,  0,
       22,  0, 22, 22, 22,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22, 22, 22,
       22,  0, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [19]:
plt_obj = dm.superset_allele_mask(am_43, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
aps_44, am_44 = sa_117_1685.snps_from_aps_value(44, am_219_26)
aps_44

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [22]:
plt_obj = dm.superset_allele_mask(am_44, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [23]:
aps_46, am_46 = sa_117_1685.snps_from_aps_value(46, am_219_26)
aps_46

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [24]:
plt_obj = dm.superset_allele_mask(am_46, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [25]:
aps_47, am_47 = sa_117_1685.snps_from_aps_value(47, am_219_26)
aps_47

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [26]:
plt_obj = dm.superset_allele_mask(am_47, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [27]:
aps_53, am_53 = sa_117_1685.snps_from_aps_value(53, am_219_26)
aps_53

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [28]:
plt_obj = dm.superset_allele_mask(am_53, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)