In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_49_136 = snp_anal.series_anal_cls(dm.di_49_136, sm.series_data)
am_49_136 = dm.allele_mask_from_index(dm.di_49_136)

<h3>Series 49_136</h3>
<div style="width:700px">
<p>
This notebook documents the series 49_136 and its 49 SNPs. The 1000 genomes data include
include 4823 chromosome 2 samples that express none of these 49 SNPs and 125 that express all
49 of them.  
<p>
The series 49_136 is the one in the 28_434 hierarchy expressed by the smallest number of
chromosome samples that is part of both the hierarchy that includes just 117_1685 and the
one that includes 13_1696.  All but 1 of the samples have lost 1 of the 117_1685 SNPs.
62 of them express 114 through 116 SNP fragments of 117_1685.  The other 74 samples
express 105 through 107 SNP fragments of 117_1685.
<p>
63 of the samples express all 13 13_1696 SNPs.  Another 11 express 12 of them.  60 of the
samples express none of the 13_1696 SNPs.  The other 2 samples express 1 or 2 of them.
<p>
All 136 samples express 106 throught 110 SNP fragments of 123_1561, 2 through 8 SNP fragments
of 62_1265 and 1 through 3 SNP fragments of 193_843.
</div>

In [2]:
HTML(dm.series_html(dm.di_49_136))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_49_136], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
plt_obj = dm.superset_yes_no([dm.di_49_136, dm.di_13_1696], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [6]:
HTML(plt_obj.get_html())

In [7]:
plt_obj = dm.superset_yes_no([dm.di_49_136], [dm.di_13_1696], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [8]:
HTML(plt_obj.get_html())

In [9]:
count_data = sa_49_136.unique_snps_per_allele()
count_data

array([(0, 4823), (1, 33), (3, 6), (4, 1), (10, 2), (38, 1), (40, 4),
       (41, 2), (44, 5), (45, 2), (47, 1), (48, 3), (49, 125)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
count_data = sa_117_1685.unique_snps_per_allele(am_49_136)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [11]:
count_data

array([(105, 3), (106, 69), (107, 2), (114, 2), (115, 7), (116, 53)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [12]:
an.sa_117_1685.alleles_per_snp(am_49_136)

array([ 59,  62,  63,  62,  62,  62,  62,  62,  62,  61, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 127, 136, 136, 136, 136, 136, 136, 136, 136, 136, 135,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,   1,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136])

In [13]:
count_data = an.sa_13_1696.unique_snps_per_allele(am_49_136)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [14]:
count_data

array([(0, 60), (1, 1), (2, 1), (12, 11), (13, 63)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [15]:
count_data = sa_123_1561.unique_snps_per_allele(am_49_136)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [16]:
count_data

array([(106, 1), (107, 11), (108, 53), (109, 53), (110, 18)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [17]:
an.sa_123_1561.alleles_per_snp(am_49_136)

array([136, 136, 136, 136,   0,  74,   0, 136, 136,   1,   2, 136, 136,
       136,   0,  17,   4,   0, 136, 135,   0, 136, 136,   0, 136, 136,
       136, 136, 136, 136, 136, 136,   0, 135, 136, 136, 136, 136, 136,
       136, 136, 135, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136,   0, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
       136, 120, 136, 136, 136, 136,   0, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136, 136, 135, 136, 136, 136, 136, 136,
       136,   0, 136, 136, 136, 134, 136, 136, 136, 136, 136, 136, 136,
       136, 136, 136, 136, 136, 136])

In [18]:
aps_110, am_110 = an.sa_123_1561.snps_from_aps_value(110, am_49_136)
aps_110

array([18, 18, 18, 18,  0, 17,  0, 18, 18,  1,  2, 18, 18, 18,  0, 16,  4,
        0, 18, 18,  0, 18, 18,  0, 18, 18, 18, 18, 18, 18, 18, 18,  0, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18,  0, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 14, 18, 18, 18, 18,  0,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18,  0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18])

In [19]:
aps_109, am_109 = an.sa_123_1561.snps_from_aps_value(109, am_49_136)
aps_109

array([53, 53, 53, 53,  0, 53,  0, 53, 53,  0,  0, 53, 53, 53,  0,  1,  0,
        0, 53, 53,  0, 53, 53,  0, 53, 53, 53, 53, 53, 53, 53, 53,  0, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53,  0, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 52, 53, 53, 53, 53,  0,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53,  0, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53])

In [20]:
aps_108, am_108 = an.sa_123_1561.snps_from_aps_value(108, am_49_136)
aps_108

array([53, 53, 53, 53,  0,  2,  0, 53, 53,  0,  0, 53, 53, 53,  0,  0,  0,
        0, 53, 53,  0, 53, 53,  0, 53, 53, 53, 53, 53, 53, 53, 53,  0, 53,
       53, 53, 53, 53, 53, 53, 53, 52, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53,  0, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 52, 53, 53, 53, 53,  0,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53,  0, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53])

In [21]:
count_data = sa_62_1265.unique_snps_per_allele(am_49_136)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [22]:
count_data

array([(2, 18), (3, 35), (4, 20), (5, 21), (6, 17), (7, 22), (8, 3)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [23]:
an.sa_62_1265.alleles_per_snp(am_49_136)

array([ 61, 136, 136,  65,  65,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   4,   0,   0,   0,   4,   4,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,
         0,  90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  40])

In [24]:
aps_7, am_7 = an.sa_62_1265.snps_from_aps_value(7, am_49_136)
aps_7

array([22, 22, 22, 21, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 21])

In [25]:
aps_6, am_6 = an.sa_62_1265.snps_from_aps_value(6, am_49_136)
aps_6

array([17, 17, 17, 17, 17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8])

In [26]:
aps_5, am_5 = an.sa_62_1265.snps_from_aps_value(5, am_49_136)
aps_5

array([11, 21, 21, 12, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9])

In [27]:
aps_4, am_4 = an.sa_62_1265.snps_from_aps_value(4, am_49_136)
aps_4

array([ 8, 20, 20, 12, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2])

In [28]:
aps_3, am_3 = an.sa_62_1265.snps_from_aps_value(3, am_49_136)
aps_3

array([ 0, 35, 35,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [29]:
aps_2, am_2 = an.sa_62_1265.snps_from_aps_value(2, am_49_136)
aps_2

array([ 0, 18, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [30]:
count_data = sa_193_843.unique_snps_per_allele(am_49_136)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [31]:
count_data

array([(1, 7), (2, 128), (3, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [32]:
an.sa_193_843.alleles_per_snp(am_49_136)

array([58,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, 75, 75,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 40,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])