In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_25_27 = snp_anal.series_anal_cls(dm.di_25_27, sm.series_data)
am_25_27 = dm.allele_mask_from_index(dm.di_25_27)

<h3>Series 25_27</h3>
<div style="width:700px">
<p>
This notebook documents the series 25_27 and its 25 SNPs. The 1000 genomes data include
include 4974 chromosome 2 samples that express none of these 25 SNPs and 27 that express all
25 of them.
<p>
The series 25_27 has selected part of the 28_434 hierarchy that expresses 117_1685 and 123_1561.
All 27 chromosome samples that express 25_27 also express 117_1685.  Only 25 of them express
123_1561.  None of them express 62_1265 or 193_843.  But all of them express significant fragments
of all four series.
<p>
24 of the samples express all 117 117_1624 SNPs. None of them express more than 116 123_1561 SNPs.
All express 20 through 22 SNP fragments of 62_1265.  All express 54 or 55 SNP fragments of 193_843.
</div>

In [2]:
HTML(dm.series_html(dm.di_25_27))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_25_27], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
count_data = sa_25_27.unique_snps_per_allele()
count_data

array([(0, 4974), (1, 5), (2, 1), (20, 1), (25, 27)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
count_data = sa_117_1685.unique_snps_per_allele(am_25_27)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(114, 2), (115, 1), (117, 24)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
count_data = sa_123_1561.unique_snps_per_allele(am_25_27)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [9]:
count_data

array([(106, 1), (107, 1), (115, 23), (116, 2)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
spa_115, am_115 = sa_123_1561.snps_from_aps_value(115, am_25_27)
spa_115

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
        0, 23, 23,  0, 23, 23,  0, 23, 23, 23, 23, 23, 23, 23, 23,  0, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23,  0, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,  0, 23, 23, 23, 23,  0,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23,  0, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 23])

In [11]:
count_data = sa_62_1265.unique_snps_per_allele(am_25_27)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [12]:
count_data

array([(20, 18), (21, 1), (22, 8)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [13]:
an.sa_62_1265.alleles_per_snp(am_25_27)

array([27, 27, 27,  9,  9, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27,  0, 27, 27,  0, 27,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [14]:
spa_20, am_20 = sa_62_1265.snps_from_aps_value(20, am_25_27)
spa_20

array([18, 18, 18,  0,  0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18,  0, 18, 18,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [15]:
spa_22, am_22 = sa_62_1265.snps_from_aps_value(22, am_25_27)
spa_22

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 0, 8,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
count_data = sa_193_843.unique_snps_per_allele(am_25_27)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [17]:
count_data

array([(54, 1), (55, 26)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [18]:
an.sa_193_843.alleles_per_snp(am_25_27)

array([26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  0, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
        0, 27, 27,  0,  0,  0, 27, 27,  0, 27,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])