In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_22_35 = snp_anal.series_anal_cls(dm.di_22_35, sm.series_data)
am_22_35 = dm.allele_mask_from_index(dm.di_22_35)
am_22_35_not_219_26 = dm.yes_allele_mask_not_or_indexes(am_22_35, [dm.di_219_26])

<h3>Series 22_35</h3>
<div style="width:700px">
<p>
This notebook documents the series 22_35 and its 22 SNPs. The 1000 genomes chromosome 2 samples
are almost perfectly divided between those that express none of the 22_35 SNPs and those that 
express all of them.  There are 4972 samples that express none of them and 34 samples that express
all 22. The remaining samples include 1 that expresses 21 of the SNPs and 1 that express 1 of them.
<p>
The series extends over 423,000 DNA bases.  It covers the upper part of the same chromosome 2 region
as 117_1685, 123_1561, 62_1265, and 193_843.  All of the samples that express 22_35 also express
123_1561. None of them express 117_1685, 62_1265, or 193_843.  But, all of them do express significant
fragments of 117_1685, and 62_1265.
<p>
The 35 samples that express 22_35 include 26 that express 219_26.  Fragment analysis and analysis
of series hierarchies show that the 9 samples that do not express 219_26 have a well defined
common history.  All 9 samples belong to South Asian populations.  They include 5 that express
the series 95_176 and 51_176.  The 146 SNPs in this pair of series are mostly expressed by 139
East Asian samples that express its 146 SNPs along with the 10 from series 6_1503 and 4_1699 that
are the lower region series of the EUR tree root.
</div>

In [2]:
HTML(dm.series_html(dm.di_22_35))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_22_35], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [17]:
count_data = sa_22_35.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [18]:
count_data

array([(0, 4972), (1, 1), (21, 1), (22, 34)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
count_data = sa_117_1685.unique_snps_per_allele(am_22_35)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [6]:
count_data

array([(43, 22), (44, 1), (46, 1), (47, 1), (53, 1), (58, 1), (59, 8)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
sa_117_1685.alleles_per_snp(am_22_35)

array([ 1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, 35,  3,  0,  3,  0,  0,
        0,  0,  0, 35, 11,  0,  0,  0, 35,  0,  0,  0, 12,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 23,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0, 35, 35, 35, 35, 35,
       35, 35,  9, 35, 10, 10, 35,  9, 34, 35,  9, 35,  9, 35, 10, 35,  9,
       35,  9, 34, 35, 35, 10, 10, 10, 10, 11, 35, 35, 35, 35, 35, 35, 35,
       35,  9, 35, 35, 35, 35, 35, 34, 35, 35, 35, 35, 35, 35, 35])

In [19]:
count_data = sa_117_1685.unique_snps_per_allele(am_22_35_not_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [20]:
count_data

array([(58, 1), (59, 8)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [21]:
sa_117_1685.alleles_per_snp(am_22_35_not_219_26)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0,
       0, 0, 9, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9,
       9, 9])

In [22]:
count_data = sa_123_1561.unique_snps_per_allele(am_22_35)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [23]:
count_data

array([(119, 1), (121, 3), (122, 5), (123, 26)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [24]:
count_data = sa_123_1561.unique_snps_per_allele(am_22_35_not_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [25]:
count_data

array([(119, 1), (121, 3), (122, 5)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
sa_123_1561.alleles_per_snp(am_22_35_not_219_26)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 7, 9, 9, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9])

In [11]:
count_data = sa_62_1265.unique_snps_per_allele(am_22_35)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [12]:
count_data

array([(47, 13), (48, 13), (49, 9)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [13]:
sa_62_1265.alleles_per_snp(am_22_35)

array([ 0,  0,  0,  0,  0, 35, 35,  0, 35, 35, 35, 35, 35, 35, 35, 35,  0,
       35, 35, 35, 35, 34, 35, 35, 35, 35, 35, 35, 35,  0, 35, 35, 35, 35,
       35, 35, 35, 35,  0, 35, 23, 35, 35, 35, 35,  0,  0, 35, 35, 35, 35,
       35, 35, 35,  0, 35, 35,  0, 35,  9, 35, 35])

In [27]:
count_data = sa_62_1265.unique_snps_per_allele(am_22_35_not_219_26)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [28]:
count_data

array([(49, 9)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [30]:
sa_62_1265.alleles_per_snp(am_22_35_not_219_26)

array([0, 0, 0, 0, 0, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 9, 9, 9, 9, 0,
       0, 9, 9, 9, 9, 9, 9, 9, 0, 9, 9, 0, 9, 9, 9, 9])

In [14]:
count_data = sa_193_843.unique_snps_per_allele(am_22_35)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [15]:
count_data

array([(0, 25), (1, 9), (2, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [36]:
plt_obj = dm.superset_yes_no([dm.di_22_35, dm.di_7_1760], [dm.di_219_26], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [37]:

HTML(plt_obj.get_html())

In [38]:
plt_obj = dm.superset_yes_no([dm.di_22_35], [dm.di_7_1760, dm.di_219_26], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [39]:

HTML(plt_obj.get_html())