In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_117_1685 = snp_anal.series_anal_cls(dm.di_117_1685, sm.series_data)
sa_123_1561 = snp_anal.series_anal_cls(dm.di_123_1561, sm.series_data)
sa_62_1265 = snp_anal.series_anal_cls(dm.di_62_1265, sm.series_data)
sa_193_843 = snp_anal.series_anal_cls(dm.di_193_843, sm.series_data)
sa_180_251 = snp_anal.series_anal_cls(dm.di_180_251, sm.series_data)
am_180_251 = dm.allele_mask_from_index(dm.di_180_251)
am_not_180_251 = dm.not_or_allele_mask([dm.di_180_251])

<h3>Series 180_251</h3>
<div style="width:700px">
<p>
This notebook documents the series 180_251 and its 180 SNPs. The 1000 genomes data includes 4626
chromosome 2 samples that express none of these 180 SNPs and 184 samples that express all 180 of them.
Another 25 samples express 179 of them.  The series extends over 720,000 DNA bases in the same part
of chromosome 2 as the series 117_1685, 123_1561, 62_1265, and 193_843.
<p>
All 251 of the chromosome 2 samples that express 180_251 also express 123_1561 and 28_434.  None of
them express 117_1685, 62_1265, or 193_843.  The chromosome samples that express 180_251 are most
of those that express 123_1561 without 117_1685 and establish 123_1561 as a series distinct from
the other overlapping series that it is often associated with.
<p>
While none of the 251 samples express 117_1685, all of them do express significant fragments of it.
241 of the samples express fragments that include 61, 62, or 63 117_1685 SNPs.  The 251 samples are
close to free of any SNPs from 62_1265 or 193_843.
<p>
The data for 28_434 and 180_251 do provide some evidence for the history of 180_251.  That history
started with a chromosome that expressed 117_1685, 123_1561, 9_887, 5_588, and 28_434.  A 
recombination event with a chromosome that expressed 13_1696 was an initial step.  That step
explains the upper region of the 117_1685 SNPs in the fragments associated with 180_251.  But,
some other history must have generated the distributed pattern of the 117_1685 SNPs in the lower
region of the fragments.  Some unknown extended history must have added the 180 SNPs specific
to 180_251 to this base association of series.  The resulting association of series was
further enhanced by the additional series that appeared within the 180_251 hierarchy.  Those
series include 23_226, 6_88, 31_73, 7_21, 15_17, and 10_17.
</div>

In [2]:
HTML(dm.series_html(dm.di_180_251))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_180_251], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
plt_obj = dm.superset_yes_no([dm.di_180_251], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [5]:
HTML(plt_obj.get_html())

In [6]:
plt_obj = dm.subset_yes_no([dm.di_180_251], min_match=0.9)
plt = plt_obj.do_plot()
show(plt)

In [7]:
HTML(plt_obj.get_html())

In [8]:
count_data = sa_180_251.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [9]:
count_data

array([(162, 1), (164, 1), (166, 4), (167, 7), (169, 2), (170, 3),
       (171, 9), (173, 1), (174, 1), (176, 5), (177, 2), (178, 6),
       (179, 25), (180, 184)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
count_data = sa_180_251.unique_snps_per_allele(am_not_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [11]:
count_data

array([(0, 4626), (1, 75), (3, 8), (4, 12), (5, 7), (6, 1), (7, 1), (9, 1),
       (12, 2), (13, 5), (22, 1), (32, 1), (33, 2), (34, 1), (49, 1),
       (64, 1), (75, 1), (84, 1), (91, 1), (102, 1), (131, 2), (133, 1),
       (134, 1), (151, 1), (155, 1), (160, 2)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [12]:
count_data = an.sa_13_1696.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [13]:
count_data

array([(0, 1), (11, 1), (12, 6), (13, 243)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [14]:
count_data = sa_117_1685.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [15]:
count_data

array([(59, 1), (60, 27), (61, 164), (62, 50), (63, 2), (68, 1), (92, 4),
       (93, 1), (98, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [16]:
27 + 164 + 50

241

In [17]:
an.sa_117_1685.alleles_per_snp(am_180_251)

array([  1,   2,   1,   2,   2,   2,   2,   2,   3,   2,   2, 251, 251,
         1, 251,   1,   1,   1,   1,   1, 251, 251,   6,   6,   6, 251,
         6,   6,   6, 251,   7,   5,   6,   6,   6,   6,   6,   6,   6,
         6,   6,   6,   6,   6,   6,   5,   5,   5,   5,   5,   5,   5,
         5,   5, 101,   5,   0,   0,   0,   0,   0,   0,   0, 251, 251,
       251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251,
       251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251,
       251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 173,
       251, 251, 251, 251, 251, 250, 251, 251, 251, 251, 251, 251, 251])

In [18]:
aps_62, am_62 = an.sa_117_1685.snps_from_aps_value(62, am_180_251)
aps_62

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 50, 50,  0, 50,  0,  0,
        0,  0,  0, 50, 50,  0,  0,  0, 50,  0,  0,  0, 50,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 50,  0,  0,  0,  0,  0,  0,  0,  0, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [19]:
aps_61, am_61 = an.sa_117_1685.snps_from_aps_value(61, am_180_251)
aps_61

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 164, 164,
         0, 164,   0,   0,   0,   0,   0, 164, 164,   0,   0,   0, 164,
         0,   0,   0, 164,   1,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  43,   0,   0,   0,   0,   0,   0,   0,   0, 164, 164,
       164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164,
       164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164,
       164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 120,
       164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164])

In [20]:
count_data = sa_123_1561.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [21]:
count_data

array([(120, 7), (121, 9), (122, 76), (123, 159)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
count_data = sa_62_1265.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [23]:
count_data

array([(0, 245), (1, 5), (5, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [24]:
count_data = sa_193_843.unique_snps_per_allele(am_180_251)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [25]:
count_data

array([(0, 244), (1, 5), (5, 1), (8, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
plt_obj = dm.superset_allele_mask(am_61, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [27]:
HTML(plt_obj.get_html())

In [28]:
plt_obj = dm.superset_allele_mask(am_61, [dm.di_180_251, dm.di_9_1170], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [29]:
HTML(plt_obj.get_html())

In [30]:
di_31_73 = 353342
plt_obj = dm.superset_allele_mask(am_61, [dm.di_180_251, di_31_73], [dm.di_9_1170], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [31]:
HTML(plt_obj.get_html())

In [32]:
plt_obj = dm.superset_allele_mask(am_61, [dm.di_180_251], [di_31_73, dm.di_9_1170], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [33]:
HTML(plt_obj.get_html())

In [34]:
plt_obj = dm.superset_allele_mask(am_61, [dm.di_180_251], [dm.di_9_1170], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [35]:
HTML(plt_obj.get_html())

In [36]:
plt_obj = dm.superset_allele_mask(am_62, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [37]:
HTML(plt_obj.get_html())