In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_32_1361 = snp_anal.series_anal_cls(dm.di_32_1361, sm.series_data)
sa_81_857 = snp_anal.series_anal_cls(dm.di_81_857, sm.series_data)

<h3>Series 81_857</h3>
<div style="width:700px">
<p>
This notebook documents the series 81_857 and its 81 SNPs. The 1000 genomes data includes
3331 samples that express none of the 81 SNPs and 583 that express all 81 of them.  Another 209
express 80 of these SNPs.  The series extends over more than 278,000 DNA bases in the same
upper part of the studied region as 64_1575 in the EUR tree.  Like 64_1575, a relatively large
number of samples do express some fragment of 81_857.
<p>
All 857 81_857 samples express the series 24_1504, 4_1442, 7_1303, and 5_12
96. 856 of the samples
express 7_1760 and 6_1114.  850 express 13_1227.  This pattern is consistent with the idea that
all of these series have an history as a single series of SNPs that has fragmented over time.
<p>
The 857 samples include 781 that express 32_1361, 546 that express 9_944, and 259 express 5_684.
<p>
The basis plot for 81_857 without 32_1361, 9_944, or 5_684  does not show much sign of any specific
selective advantage.  The 76 samples that express 81_857 without any of these series appear
to have resulted from a variety of recombination events.
<p>
The basis plot for 81_857 and 32_1361 without 9_944 or 5_684 shows an history of several selection
events.  Several of them involve hierarchies selected by series expressed by samples from African
populations.
<p>
The basis plot for 81_857, 32_1361, 9_944 without 5_684 shows an history of several additional selection
events.  The 150 samples that only express 81_857, 32_1361, and 9_944 are one example.  Significant numbers
of samples from African and East Asian populations are part of this example.  But, both of those populations
are underexpressed.  The biggest overexpression is for the 38 samples from American populations.  European
and South Asian populations are also overexpressed.  Samples from African and East Asian populations are
absent from most of the other selective events from this plot.
<p>
The last basis plot is for 81_857 and 5_684.  The 79 samples from this plot that express either 4_67 or 5_47
as a basis are very strongly overexpressed for East Asian populations.  The 87 samples from this plot that
express 5_684 for a basis are overexpressed for East Asian, American, and South Asian populations.  Only 1
of the samples comes from Europe and none from Africa.  This plot understates the role of 5_684 and its
East Asian overexpression because many of the East Asian samples that express 5_684 as a basis are derived
from recombination events that replaced 81_857 with 64_1575, 10_2206, and 7_1868.  The 22 samples from this
plot that express the series 4_25 as a basis all come from East Asian populations.
<p>
The population distributions are very different for the 93 samples from this plot that express the
series 7_59, 14_43, 4_37, or 4_35 as a basis.  None of those samples come from East Asian populations.
</div>

In [2]:
HTML(dm.series_html(dm.di_81_857))

In [3]:
count_data = sa_81_857.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [4]:
count_data

array([(0, 3331), (1, 272), (2, 13), (3, 2), (4, 5), (5, 6), (6, 62),
       (7, 47), (8, 4), (10, 2), (12, 10), (13, 76), (14, 1), (15, 7),
       (16, 31), (17, 2), (18, 2), (19, 11), (20, 1), (22, 3), (23, 1),
       (24, 8), (26, 1), (27, 1), (30, 1), (33, 1), (36, 5), (37, 2),
       (38, 8), (39, 19), (40, 2), (41, 5), (42, 42), (43, 3), (46, 1),
       (47, 3), (48, 1), (49, 6), (55, 37), (56, 6), (57, 56), (62, 3),
       (63, 6), (64, 12), (65, 22), (66, 7), (67, 4), (78, 10), (79, 55),
       (80, 209), (81, 583)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
aps_6, am_6 = sa_81_857.snps_from_aps_value(6)
aps_6

array([ 0,  1,  1,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,
        0, 52, 61,  0,  0, 58, 61,  0,  0,  0,  0,  0,  0,  0, 61,  0,  0,
        0,  0, 61,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [6]:
aps_13, am_13 = sa_81_857.snps_from_aps_value(13)
aps_13

array([76, 76,  0,  0,  2,  2,  2,  2,  2,  2,  2,  2, 76, 76, 76, 74, 74,
       74, 74, 74,  0, 74, 74,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       74,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [7]:
aps_42, am_42 = sa_81_857.snps_from_aps_value(42)
aps_42

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 42, 42, 42,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2])

In [8]:
aps_55, am_55 = sa_81_857.snps_from_aps_value(55)
aps_55

array([37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37,  0, 37,  0,  0,  0,  0,  0,  0,  0, 37, 37, 37,
        0,  0, 37,  0,  0, 37, 37,  0, 37,  0, 37, 37,  0,  0, 37,  0,  0,
       37,  0, 37, 37,  0,  0,  0,  0,  0,  0, 37,  0, 37])

In [9]:
aps_57, am_57 = sa_81_857.snps_from_aps_value(57)
aps_57

array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  4, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
       56, 56, 56, 56, 56, 54, 56, 54, 54, 54, 54, 54, 54, 54, 56, 56, 56,
       54, 54, 56, 54, 54, 56, 56, 54, 56, 54, 56, 56, 54, 54, 56, 54, 54,
       56, 54, 56, 56, 54, 54, 54, 54, 54, 56, 56, 56, 54])

In [10]:
aps_65, am_65 = sa_81_857.snps_from_aps_value(65)
aps_65

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [11]:
plt_obj = dm.superset_yes_no([dm.di_81_857], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [12]:
plt_obj = dm.superset_yes_no([dm.di_81_857], [dm.di_32_1361, dm.di_9_944, dm.di_5_684], min_match=0.001)
plt_obj.do_plot()
am_back = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [13]:
plt_obj = dm.basis_yes_no([dm.di_81_857], [dm.di_32_1361, dm.di_9_944, dm.di_5_684])
plt = plt_obj.do_basis_plot()
show(plt)

In [14]:
HTML(plt_obj.get_basis_html())

In [15]:
plt_obj = dm.basis_yes_no([dm.di_81_857, dm.di_32_1361], [dm.di_9_944, dm.di_5_684])
plt = plt_obj.do_basis_plot()
show(plt)

In [16]:
HTML(plt_obj.get_basis_html())

In [17]:
plt_obj = dm.basis_yes_no([dm.di_81_857, dm.di_9_944], [dm.di_5_684])
plt = plt_obj.do_basis_plot()
show(plt)

In [18]:
HTML(plt_obj.get_basis_html())

In [19]:
plt_obj = dm.basis_yes_no([dm.di_81_857, dm.di_5_684])
plt = plt_obj.do_basis_plot()
show(plt)

In [20]:
HTML(plt_obj.get_basis_html())