In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_5_684 = snp_anal.series_anal_cls(dm.di_5_684, sm.series_data)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)

<h3>Series 5_684</h3>
<div style="width:700px">
<p>
This notebook documents the series 5_684 and its 5 SNPs. The 1000 genomes data sample
SNP counts for 5_684 are 4214 samples 0 SNPs, 29 samples 1 SNP, 13 samples 2 SNPs, 14 samples 3
SNPs, 24 samples 4 SNPs, and 684 samples 5 SNPs.  The 5 SNP series extends over more than
416,000 DNA bases.  
<p>
The 684 samples that express 5_684 include 444 from East Asian populations, 145 from South Asian
populations, 63 from American populations, 31 from European populations, and 1 from an African
population.
<p>
The series 5_684 appears to have emerged from the standard EAS tree root that includes the series
13_1696, 9_944, 32_1361, and 81_857.  But chromosomes expressing 5_684 have been subject to more
extensive recombination events than those for the same region of the EUR or SAS trees.  Only
259 of the 684 samples express 81_857.  333 express 64_1575 as a result of recombination
events that have associated 64_1575, 10_2206, and 7_1868 from the EUR tree root with 5_684.
There are 90 samples that express 4_815 instead of 13_1696 with 5_684 as a result of recombination
events with the lower region of the SAS tree.  Another 18 samples have resulted from recombination events
that associated 5_1460 from the SAS tree with 5_684.  Those recombination events lost the top 3 SNPs of 9_944.
Another 9 samples have resulted from recombination events that associated 5_684 with 26_1414, 64_1575,
10_2206, and 7_1868.  Those recombination events also resulted in the loss of the top 3 SNPs of 9_944.
</div>

In [2]:
HTML(dm.series_html(dm.di_5_684))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_5_684], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = an.sa_5_684.unique_snps_per_allele()
count_data

array([(0, 4214), (1, 29), (2, 13), (3, 14), (4, 54), (5, 684)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
am_5_684_4_815 = dm.and_allele_mask([dm.di_5_684, dm.di_4_815])

In [6]:
an.sa_117_1685.alleles_per_snp(am_5_684_4_815)

array([89, 89, 90, 90, 90, 90, 90, 90, 90, 90, 89, 90, 90, 90, 90, 90, 90,
       90, 89, 89, 90, 90, 90, 90, 90, 90, 90, 90, 89, 90, 90, 90, 90, 90,
       90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
       90, 90, 90, 89, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
       90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
       90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 89,  0,  0,  0,  0,  2,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0])

In [7]:
an.sa_123_1561.alleles_per_snp(am_5_684_4_815)

array([89, 89,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0])

In [8]:
an.sa_62_1265.alleles_per_snp(am_5_684_4_815)

array([88, 89, 89, 90, 90, 89, 89, 89,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [9]:
an.sa_193_843.alleles_per_snp(am_5_684_4_815)

array([89, 89, 89, 89, 89, 89, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
       90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 89,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [10]:
an.sa_9_944.alleles_per_snp(am_5_684_4_815)

array([ 0,  0, 90, 90, 90, 90, 90, 79, 79])

In [11]:
an.sa_5_684.alleles_per_snp(am_5_684_4_815)

array([90, 90, 90, 90, 90])

In [12]:
plt_obj = dm.superset_yes_no([dm.di_5_684, dm.di_4_815, dm.di_32_1361], [dm.di_9_944], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
sa_9_944.alleles_per_snp(am)

array([ 0,  0, 79, 79, 79, 79, 79, 79, 79])

In [15]:
plt_obj = dm.superset_yes_no([dm.di_5_684, dm.di_5_1460], [dm.di_4_815, dm.di_9_944], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
sa_9_944.alleles_per_snp(am)

array([18, 18, 18, 18, 18, 18,  0,  0,  0])

In [18]:
plt_obj = dm.superset_yes_no([dm.di_5_684, dm.di_26_1414], [dm.di_4_815, dm.di_9_944], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
sa_9_944.alleles_per_snp(am)

array([9, 9, 9, 9, 9, 9, 0, 0, 0])

In [21]:
plt_obj = dm.superset_yes_no([dm.di_5_684], [dm.di_26_1414, dm.di_5_1460, dm.di_32_1361, dm.di_9_944], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [22]:
HTML(plt_obj.get_html())

In [23]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 0, 1, 1, 1, 1, 1, 0])