In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)

<h3>Series 9_944</h3>
<div style="width:700px">
<p>
This notebook documents the series 9_944 and its 9 SNPs. The 1000 genomes data includes
3610 samples that express none of the 9 SNPs and 925 that express all 9 of them.  Another 19
express 8 of these SNPs.  The series extends over more than 591,000 DNA bases in the same
lower part of the studied region as 6_1503 and 4_1699 in the EUR tree or 117_1685, 123_1561,
62_1265, and 193_843 in the SAS tree.
<p>
The EAS tree appears more subject to recombination events than either the EUR or SAS trees.
One measure is the different associations of 9_944 with different series in the upper part
of the studied region.  Only 546 of samples expressing 9_944 associate it with 81_857.
Another measure is the number of samples expressing 5_684 that have lost 9_944.  Out
of the 684 5_684 samples only 562 express 9_944. Another measure is the 395 samples that express
more than 2 9_944 SNPs but less than 8.  Those fragments and some of the series associated with
them are explored in this notebook.
</div>

In [2]:
HTML(dm.series_html(dm.di_9_944))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_9_944], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
plt_obj = dm.superset_yes_no([dm.di_9_944], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [5]:
HTML(plt_obj.get_html())

In [6]:
count_data = sa_9_944.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(0, 3610), (1, 28), (2, 31), (3, 81), (4, 52), (5, 24), (6, 103),
       (7, 135), (8, 19), (9, 925)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
81+52+24+103+135 

395

In [9]:
aps_2, am_2 = sa_9_944.snps_from_aps_value(2)
aps_2

array([27,  5, 20,  0,  2,  4,  2,  2,  0])

In [10]:
aps_3, am_3 = sa_9_944.snps_from_aps_value(3)
aps_3

array([41,  1, 41,  0,  0, 45, 40, 40, 35])

In [11]:
plt_obj = dm.superset_allele_mask(am_3, [dm.di_5_1460], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [12]:
HTML(plt_obj.get_html())

In [13]:
sa_9_944.alleles_per_snp(am)

array([41,  1, 41,  0,  0, 40,  0,  0,  0])

In [14]:
am_3_not_5_1460 = dm.yes_allele_mask_not_or_indexes(am_3, [dm.di_5_1460])

In [15]:
plt_obj = dm.superset_allele_mask(am_3_not_5_1460, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
sa_9_944.alleles_per_snp(am)

array([ 0,  0,  0,  0,  0,  5, 40, 40, 35])

In [18]:
aps_4, am_4 = sa_9_944.snps_from_aps_value(4)
aps_4

array([ 6,  2,  6,  4,  3, 49, 46, 46, 46])

In [19]:
plt_obj = dm.superset_allele_mask(am_4, [dm.di_9_39], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
sa_9_944.alleles_per_snp(am)

array([ 0,  0,  0,  0,  0, 39, 39, 39, 39])

In [22]:
aps_6, am_6 = sa_9_944.snps_from_aps_value(6)
aps_6

array([ 97,  95,  97, 102, 100, 103,   9,   9,   6])

In [23]:
plt_obj = dm.superset_allele_mask(am_6, [dm.di_5_1460], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [24]:
HTML(plt_obj.get_html())

In [25]:
sa_9_944.alleles_per_snp(am)

array([77, 77, 77, 77, 77, 77,  0,  0,  0])

In [26]:
aps_7, am_7 = sa_9_944.snps_from_aps_value(7)
aps_7

array([ 37,  20, 118, 132, 132, 132, 135, 135, 104])

In [27]:
plt_obj = dm.superset_allele_mask(am_7, [dm.di_4_815], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [28]:
HTML(plt_obj.get_html())

In [29]:
sa_9_944.alleles_per_snp(am)

array([ 0,  0, 82, 82, 82, 82, 82, 82, 82])