In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_32_1361 = snp_anal.series_anal_cls(dm.di_32_1361, sm.series_data)
sa_81_857 = snp_anal.series_anal_cls(dm.di_81_857, sm.series_data)

<h3>Series 32_1361</h3>
<div style="width:700px">
<p>
This notebook documents the series 32_1361 and its 32 SNPs.  The series 32_1361 is a central
component of the EAS tree root.  It ranges over an 93,000 DNA base sequence that covers the
upper part of the gene r3hdm1.  This part of the studied region of chromosome 2 is similar
to that covered by 26_1414 in the EUR tree root.
<p>
The 1000 genomes data includes 3312 chromosome 2 samples that express none of these 32 SNPs
and 1332 samples that express all 32 of them.  Another 24 samples express 31 of them.
The fragments of the 32 SNPs include a specific 24 SNP fragment that is expressed by 134
chromosome samples.  That fragment is associated with the hierarchy that was selected by
the series 74_210.
<p>
The role of 32_1361 in the EAS tree is analyzed in the the notebooks [eas_root](../eas_root.ipynb)
and [eas_super_32_1361](../eas_super_32_1361.ipynb).  This notbook explores hierarchies
rooted in 32_1361 that are outside the EAS tree and overexpressed in African populations.
These hierarchies establish an history of events that selected the upper region of the EAS
tree before the emergence from Africa
<p>
The hierarchies selected by the series 24_24, 15_24, 8_28, and 12_29 have an
added interest.  Those hierarchies all include the series 4_1699 in their roots.
That series is a component of the EUR tree root.  It is also part of the series
expressed by 139 East Asian chromosome samples that express the series
6_1503, 4_1699, 95_176, and 51_176.
<p>
The other hierarhcy rooted in 32_1361 was selected by the series 9_39.  The root
of that hierarchy resulted from a recombination event between an hierarchy of the
SAS tree selected by the series 8_267 and the upper region of the EAS tree root.
But, no East Asian, only 1 African, and 3 South Asian samples express 9_39.  It
is overexpressed in European and American populations.
</div>

In [2]:
HTML(dm.series_html(dm.di_32_1361))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_32_1361], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
plt_obj = dm.superset_yes_no([dm.di_32_1361], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [5]:
HTML(plt_obj.get_html())

In [6]:
count_data = sa_32_1361.unique_snps_per_allele()
count_data

array([(0, 3312), (1, 137), (2, 1), (3, 1), (4, 7), (7, 7), (9, 1),
       (10, 5), (11, 2), (13, 1), (15, 20), (16, 1), (17, 9), (20, 2),
       (22, 1), (23, 2), (24, 134), (25, 2), (26, 1), (28, 1), (29, 2),
       (30, 3), (31, 24), (32, 1332)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
aps_24, am_24 = sa_32_1361.snps_from_aps_value(24)
aps_24

array([134, 134, 134, 134, 134, 134, 134, 134, 134,   0, 134, 134,   0,
       134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134, 134,
         0,   0,   0,   0,   0,   0])

In [8]:
plt_obj = dm.superset_allele_mask(am_24, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [9]:
HTML(plt_obj.get_html())

In [10]:
di_26_17 = 353258
di_4_16 = 353251
di_5_20 = 353580
di_11_21 = 353946
di_24_24 = 353359
di_8_28 = 353368
di_12_29 = 353243
di_9_39 = 353559
di_8_41 = 353559
di_18_60 = 353282
di_15_24 = 353305
plt_obj = dm.superset_yes_no([dm.di_32_1361],
                               [di_26_17, di_4_16, di_5_20, di_11_21, di_15_24, di_24_24,
                                di_8_28, di_12_29, di_9_39, di_8_41, di_18_60,
                                dm.di_9_944, dm.di_5_684], min_match=0.001)
plt_obj.do_plot()
am_back = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [11]:
sa_32_1361.unique_snps_per_allele(am_back)

array([(29, 2), (30, 1), (31, 20), (32, 109)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [12]:
sa_32_1361.alleles_per_snp(am_back)

array([132, 132, 132, 132, 132, 132, 132, 132, 132, 130, 132, 132, 130,
       132, 132, 132, 132, 132, 132, 132, 132, 132, 132, 132, 132, 131,
       130, 132, 114, 131, 131, 131])

In [13]:
sa_81_857.unique_snps_per_allele(am_back)

array([(0, 46), (1, 1), (6, 1), (7, 3), (8, 1), (13, 2), (24, 6), (42, 2),
       (48, 1), (49, 5), (55, 3), (79, 1), (80, 10), (81, 50)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [14]:
sa_81_857.alleles_per_snp(am_back)

array([75, 75, 73, 73, 75, 75, 74, 74, 74, 75, 75, 74, 74, 74, 74, 70, 72,
       72, 72, 72, 72, 72, 72, 72, 60, 66, 66, 66, 66, 66, 71, 66, 67, 71,
       72, 72, 72, 72, 72, 69, 72, 69, 67, 67, 71, 67, 67, 67, 70, 70, 70,
       67, 71, 74, 67, 67, 71, 74, 67, 70, 67, 70, 70, 67, 67, 74, 67, 67,
       70, 67, 74, 70, 67, 67, 67, 67, 67, 67, 70, 67, 69])

In [15]:
plt_obj = dm.superset_yes_no([di_26_17], min_match=0.5)
plt = plt_obj.do_plot()
am_26_17 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
sa_32_1361.alleles_per_snp(am_26_17)

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [18]:
sa_81_857.alleles_per_snp(am_26_17)

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [19]:
plt_obj = dm.superset_yes_no([di_4_16], min_match=0.5)
plt = plt_obj.do_plot()
am_4_16 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
sa_32_1361.alleles_per_snp(am_4_16)

array([16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [22]:
sa_81_857.alleles_per_snp(am_4_16)

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [23]:
plt_obj = dm.superset_yes_no([di_11_21], min_match=0.5)
plt = plt_obj.do_plot()
am_11_21 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [24]:
HTML(plt_obj.get_html())

In [25]:
sa_32_1361.alleles_per_snp(am_11_21)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [26]:
sa_81_857.alleles_per_snp(am_11_21)

array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21])

In [27]:
plt_obj = dm.superset_yes_no([di_15_24], min_match=0.5)
plt = plt_obj.do_plot()
am_15_24 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [28]:
HTML(plt_obj.get_html())

In [29]:
sa_32_1361.alleles_per_snp(am_15_24)

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24])

In [30]:
sa_81_857.alleles_per_snp(am_15_24)

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 23, 23, 23, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 19, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [31]:
plt_obj = dm.superset_yes_no([di_8_28], min_match=0.5)
plt = plt_obj.do_plot()
am_8_28 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [32]:
HTML(plt_obj.get_html())

In [33]:
sa_32_1361.alleles_per_snp(am_8_28)

array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28])

In [34]:
sa_81_857.alleles_per_snp(am_8_28)

array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28])

In [35]:
plt_obj = dm.superset_yes_no([di_12_29], min_match=0.5)
plt = plt_obj.do_plot()
am_12_29 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [36]:
HTML(plt_obj.get_html())

In [37]:
sa_32_1361.alleles_per_snp(am_12_29)

array([29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29])

In [38]:
sa_81_857.alleles_per_snp(am_12_29)

array([29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 28, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 28, 28, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [39]:
plt_obj = dm.superset_yes_no([di_9_39], min_match=0.5)
plt = plt_obj.do_plot()
am_9_39 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [40]:
HTML(plt_obj.get_html())

In [41]:
sa_32_1361.alleles_per_snp(am_9_39)

array([39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39])

In [42]:
sa_81_857.alleles_per_snp(am_9_39)

array([32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 30, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 26, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29])