In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
di_14_43 = 353394
sa_14_43 = snp_anal.series_anal_cls(di_14_43, sm.series_data)
am_14_43 = dm.allele_mask_from_index(di_14_43)
sa_5_684 = snp_anal.series_anal_cls(dm.di_5_684, sm.series_data)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)

<h3>Series 14_43</h3>
<div style="width:700px">
<p>
This notebook documents the series 14_43 and its 14 SNPs. The 1000 genomes data includes 4953
chromosome 2 samples that express none of these 43 SNPs and 32 samples that express all 14 of them.
Another 11 samples express 13 of them.  The series extends over 642,000 DNA bases in the same part
of chromosome 2 as the series 5_684, 9_944, and 32_1361 from the East Asian tree.  All but 1 of
the samples that express 14_43 also express the series 7_59.  The series 7_59 has selected an
hierarchy formed from the upper region of the EAS tree root that includes the series 81_857.
<p>
Although the hierarchy selected by 14_43 comes from the EAS tree, it is not expressed by any
chromosome samples from East Asian populations.  No chromosome that expresses either 14_43
or 7_59 comes from any East Asian or African population.  The samples are heavily over expressed
for European and American populations.  Chromosome samples from South Asian populations are under expressed
but present in significant numbers.
</div>

In [2]:
HTML(dm.series_html(di_14_43))

In [3]:
plt_obj = dm.superset_yes_no([di_14_43], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_14_43.unique_snps_per_allele()
count_data

array([(0, 4953), (1, 4), (2, 1), (4, 1), (9, 3), (10, 1), (12, 2),
       (13, 11), (14, 32)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
sa_14_43.alleles_per_snp(am_14_43)

array([42, 43, 42, 43, 43, 41, 42, 40, 42, 42, 42, 43, 43, 43])

In [6]:
count_data = sa_5_684.unique_snps_per_allele(am_14_43)
count_data

array([(4, 5), (5, 38)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
sa_5_684.alleles_per_snp(am_14_43)

array([43, 43, 42, 43, 39])

In [8]:
plt_obj = dm.superset_yes_no([di_14_43, dm.di_13_1696, dm.di_5_684], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [9]:
HTML(plt_obj.get_html())

In [10]:
count_data = sa_14_43.unique_snps_per_allele(am)
count_data

array([(13, 10), (14, 28)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [11]:
count_data = sa_5_684.unique_snps_per_allele(am)
count_data

array([(5, 38)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [12]:
di_7_59 = 353917
plt_obj = dm.superset_yes_no([di_7_59, dm.di_5_1460], [di_14_43], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
plt_obj = dm.superset_yes_no([di_7_59, dm.di_5_684], [dm.di_5_1460, di_14_43], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [15]:
HTML(plt_obj.get_html())

In [16]:
plt_obj = dm.superset_yes_no([di_7_59], [dm.di_5_684, dm.di_5_1460, di_14_43], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
plt_obj = dm.superset_yes_no([di_14_43, dm.di_13_1696], [dm.di_5_684], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
count_data = sa_14_43.unique_snps_per_allele(am)
count_data

array([(14, 4)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [21]:
count_data = sa_5_684.unique_snps_per_allele(am)
count_data

array([(4, 4)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
sa_5_684.alleles_per_snp(am)

array([4, 4, 3, 4, 1])

In [23]:
sa_9_944.alleles_per_snp(am)

array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [24]:
plt_obj = dm.superset_yes_no([di_14_43], [dm.di_13_1696], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [25]:
HTML(plt_obj.get_html())

In [26]:
count_data = sa_14_43.unique_snps_per_allele(am)
count_data

array([(13, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [27]:
sa_14_43.alleles_per_snp(am)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
count_data = sa_5_684.unique_snps_per_allele(am)
count_data

array([(4, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [29]:
sa_5_684.alleles_per_snp(am)

array([1, 1, 1, 1, 0])

In [30]:
sa_9_944.alleles_per_snp(am)

array([0, 0, 1, 1, 1, 1, 1, 1, 1])

In [31]:
an.sa_117_1685.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [32]:
an.sa_123_1561.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
an.sa_62_1265.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
an.sa_193_843.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])