In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
di_4_34 = 353308
sa_4_34 = snp_anal.series_anal_cls(di_4_34, sm.series_data)
di_4_37 = 353635
sa_4_37 = snp_anal.series_anal_cls(di_4_37, sm.series_data)
am_4_34 = dm.allele_mask_from_index(di_4_34)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)
sa_5_684 = snp_anal.series_anal_cls(dm.di_5_684, sm.series_data)

<h3>Series 4_34</h3>
<div style="width:700px">
<p>
This notebook documents the series 4_34 and its 4 SNPs.  The 1000 genomes data sample SNP counts
for 4_34 are 4967 samples 0 SNPs, 1 sample 1 SNP, 0 samples 2 SNPs, 6 samples 3 SNPs, and
34 samples 4 SNPs.
<p>
Series 4_34 is another case of selection of the EAS tree where none of the samples expressing
the series come from East Asian populations.  The population sample numbers are African 0,
American 2, East Asian 0, European 5, and South Asian 27.
<p>
The history of 4_34 is associated with 4_37.  The 34 samples that express 4_34 include 19
that express 4_37 and a full hierarchy of the East Asian tree.  That hierarchy includes
5_684, 9_944, 32_1361, and 81_857.  The SNPs associated with other instances of 4_34 show
an history of a variety of events either involving recombination or lost SNPs.
</div>

In [2]:
HTML(dm.series_html(di_4_34))

In [3]:
plt_obj = dm.superset_yes_no([di_4_34], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_4_34.unique_snps_per_allele()
count_data

array([(0, 4967), (1, 1), (3, 6), (4, 34)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
count_data = sa_4_37.unique_snps_per_allele(am_4_34)
count_data

array([(0, 4), (2, 1), (3, 2), (4, 27)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
count_data = sa_9_944.unique_snps_per_allele(am_4_34)
count_data

array([(3, 1), (6, 1), (8, 1), (9, 31)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
count_data = sa_5_684.unique_snps_per_allele(am_4_34)
count_data

array([(1, 1), (3, 1), (4, 8), (5, 24)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
di_4_37 = 353635
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361, dm.di_81_857, dm.di_5_684, di_4_37], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [9]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
The two samples that express this hiearchy do not express the same fragment of 4_37 SNPs.  Both
could derive from recombination events with chromosomes that expressed the EAS tree but
not 4_37.
</div>

In [10]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361, dm.di_81_857, dm.di_5_684], 
                             [di_4_37], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [11]:
HTML(plt_obj.get_html())

In [12]:
sa_4_37.alleles_per_snp(am)

array([0, 0, 1, 1])

<div style="width:700px">
<p>
The loss of 5_684 appears due to a variety of lost SNPs
</div>

In [13]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361, dm.di_81_857, di_4_37], 
                             [dm.di_5_684], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [14]:
HTML(plt_obj.get_html())

In [15]:
sa_5_684.alleles_per_snp(am)

array([7, 7, 4, 6, 4])

<div style="width:700px">
<p>
The loss of 5_684 and 4_37 appears likely the result of lost SNPs.
</div>

In [16]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361, dm.di_81_857], 
                             [di_4_37, dm.di_5_684], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
sa_5_684.alleles_per_snp(am)

array([2, 2, 1, 1, 1])

In [19]:
sa_4_37.alleles_per_snp(am)

array([2, 2, 1, 1])

<div style="width:700px">
<p>
The loss of 4_37 appears to be a result of a recombination event with a chromsome that
expressed 64_1575, 10_2206, and 7_1868 in combination with the EAS tree hierarchy including
32_1361, 9_944, and 5_684.
</div>

In [20]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361, dm.di_7_1868], [dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
sa_4_37.alleles_per_snp(am)

array([0, 0, 0, 0])

In [23]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_32_1361], [dm.di_7_1868, dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [24]:
HTML(plt_obj.get_html())

In [25]:
sa_4_37.alleles_per_snp(am)

array([0, 0, 0, 0])

<div style="width:700px">
<p>
This association of series appears to result from a recombination event that
lost the top 6 SNPs of 9_944 and the top 4 SNPs of 5_684.
</div>

In [26]:
plt_obj = dm.superset_yes_no([di_4_34, dm.di_5_1460], [dm.di_32_1361], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [27]:
HTML(plt_obj.get_html())

In [28]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 0, 0, 0, 0, 0, 0])

In [29]:
sa_5_684.alleles_per_snp(am)

array([1, 0, 0, 0, 0])

<div style="width:700px">
<p>
This association appears to result from a recombination event with a chromosome expressing
the upper region of the EUR tree root including the series 26_1414 that resulted in the
loss of the top 3 9_944 SNPs.
</div>

In [30]:
plt_obj = dm.superset_yes_no([di_4_34], [dm.di_5_1460, dm.di_32_1361], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [31]:
HTML(plt_obj.get_html())

In [32]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 0, 0, 0])