In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
di_4_34 = 353308
sa_4_34 = snp_anal.series_anal_cls(di_4_34, sm.series_data)
am_4_34 = dm.allele_mask_from_index(di_4_34)
di_4_37 = 353635
sa_4_37 = snp_anal.series_anal_cls(di_4_37, sm.series_data)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)
sa_5_684 = snp_anal.series_anal_cls(dm.di_5_684, sm.series_data)

<h3>Series 4_37</h3>
<div style="width:700px">
<p>
This notebook documents the series 4_37 and its 4 SNPs.  The 1000 genomes data sample SNP counts
for 4_37 are 4966 samples 0 SNPs, 1 sample 1 SNP, 2 samples 2 SNPs, 2 samples 3 SNPs, and
37 samples 4 SNPs.
<p>
Series 4_37 is another case of selection of the EAS tree where none of the samples expressing
the series come from East Asian populations.  The population sample numbers are African 0,
American 3, East Asian 0, European 6, and South Asian 28.
<p>
The 37 samples that express 4_37 include 35 that express the root series of the EAS tree
including 13_1696, 9_944, 32_1361, and 81_857.  Those 35 samples include 19 that also express
4_34 and 5_684.  The other samples express associations that show histories of a variety of
recombination events and lost SNPs.  This notebook focuses on hierarchies that don't include
4_34.  Those that include both 4_34 and 4_37 are covered in the notebook [series_434](series_4_34.ipynb)
</div>

In [2]:
HTML(dm.series_html(di_4_37))

In [3]:
plt_obj = dm.superset_yes_no([di_4_37], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_4_37.unique_snps_per_allele()
count_data

array([(0, 4966), (1, 1), (2, 2), (3, 2), (4, 37)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
plt_obj = dm.superset_yes_no([di_4_37], [di_4_34], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
The loss of 4_34 from the samples expressing this hierarchy is the result of lost SNPs.
</div>

In [6]:
plt_obj = dm.superset_yes_no([di_4_37, dm.di_81_857, dm.di_13_1696, dm.di_5_684], 
                             [di_4_34], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [7]:
HTML(plt_obj.get_html())

In [8]:
sa_4_34.alleles_per_snp(am)

array([5, 4, 1, 5])

In [9]:
sa_5_684.alleles_per_snp(am)

array([6, 6, 6, 6, 6])

In [10]:
sa_9_944.alleles_per_snp(am)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

<div style="width:700px">
<p>
Both 4_34 and 5_684 appear to have been lost from the sample expressing this hierarchy
because each of those series has lost one SNP.
</div>

In [11]:
plt_obj = dm.superset_yes_no([di_4_37, dm.di_81_857, dm.di_13_1696], 
                             [dm.di_5_684, di_4_34], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [12]:
HTML(plt_obj.get_html())

In [13]:
sa_4_34.alleles_per_snp(am)

array([1, 0, 1, 1])

In [14]:
sa_5_684.alleles_per_snp(am)

array([1, 1, 1, 1, 0])

In [15]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

<div style="width:700px">
<p>
This chromosome sample appears to have lost all 4 4_34 SNPs, the lower 5 9_944 SNPs, and
the lower 2 5_684 SNPs in a recombination event between the EUR tree and the EAS tree.
The sample expressing the recombinant hierarchy comes from an European population.
</div>

In [16]:
plt_obj = dm.superset_yes_no([di_4_37, dm.di_81_857, dm.di_4_1699], [dm.di_13_1696], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
sa_4_34.alleles_per_snp(am)

array([0, 0, 0, 0])

In [19]:
sa_5_684.alleles_per_snp(am)

array([0, 0, 1, 1, 1])

In [20]:
sa_9_944.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])

<div style="width:700px">
<p>
This hierarchy appears to be the result of another recombination event where all 4 4_34 SNPs,
the lower 4 9_944 SNPs and the lowest 5_684 SNP were lost.
</div>

In [21]:
plt_obj = dm.superset_yes_no([di_4_37, dm.di_81_857], [dm.di_4_1699, dm.di_13_1696], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [22]:
HTML(plt_obj.get_html())

In [23]:
sa_4_34.alleles_per_snp(am)

array([0, 0, 0, 0])

In [24]:
sa_5_684.alleles_per_snp(am)

array([0, 1, 1, 1, 1])

In [25]:
sa_9_944.alleles_per_snp(am)

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

<div style="width:700px">
<p>
This hierarchy appears to result from the loss of the top 3 9_944
SNPs and the top 5_684 SNP in a recombination event with the upper region
of the EUR tree.  Some other event must be responsible for the loss of all
4 4_34 SNPs.
</div>

In [26]:
plt_obj = dm.superset_yes_no([di_4_37], [dm.di_81_857, di_4_34], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [27]:
HTML(plt_obj.get_html())

In [28]:
sa_4_34.alleles_per_snp(am)

array([0, 0, 0, 0])

In [29]:
sa_5_684.alleles_per_snp(am)

array([1, 1, 1, 1, 0])

In [30]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 0, 0, 0])