In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)
sa_4_911 = snp_anal.series_anal_cls(dm.di_4_911, sm.series_data)

<h3>Series 4_911</h3>
<div style="width:700px">
<p>
This notebook documents the series 4_911 and its 4 SNPs.  The 1000 genomes data includes
4001 samples that express none of its 4 SNPs and 911 samples that express all 4 of them.
The 4 SNP series covers more than  315,000 DNA bases.
<p>
The 911 samples include 762 that express the series 11_765 that is associated with lactase
persistence.  The series associations expressed by those samples are close to constant with
almost no history of recombination events.  Another 72 samples express 4_911 in association
with all the series of the EUR tree root, 6_1503, 4_1699, 26_1414, 64_1575, 10_2206, and 7_1868.
The other 77 samples express 4_911 in association with a variety of different series that
have resulted from varied histories of recombination events.  This notebook explores those
associations.
</div>

In [2]:
HTML(dm.series_html(dm.di_4_911))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_4_911], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_4_911.unique_snps_per_allele()
count_data

array([(0, 4001), (1, 37), (2, 39), (3, 20), (4, 911)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
plt_obj = dm.superset_yes_no([dm.di_4_911], [dm.di_11_765], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [6]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575], [dm.di_11_765], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [7]:
di_6_35 = 353407
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575, dm.di_7_1868, dm.di_4_1699, dm.di_10_2206], 
                             [di_6_35, dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [8]:
HTML(plt_obj.get_html())

In [9]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575, dm.di_7_1868, dm.di_4_1699, 
                              dm.di_10_2206, di_6_35], 
                             [dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [10]:
HTML(plt_obj.get_html())

In [11]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575, dm.di_7_1868, dm.di_4_1699], 
                             [dm.di_10_2206, dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [12]:
HTML(plt_obj.get_html())

In [13]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575, dm.di_7_1868, dm.di_6_1503], 
                             [dm.di_4_1699, dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [14]:
HTML(plt_obj.get_html())

In [15]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575, dm.di_7_1868], 
                             [dm.di_6_1503, dm.di_4_1699, dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_64_1575], 
                             [dm.di_7_1868, dm.di_11_765], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [18]:
HTML(plt_obj.get_html())

In [19]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206], [dm.di_64_1575, dm.di_11_765], min_match=0.001)
plt_obj.do_plot()
am_0 = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [20]:
sa_64_1575.alleles_per_snp(am_0)

array([57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
       57, 57, 57, 57, 55, 54, 53, 53, 53, 53, 53, 53, 53, 53, 52, 51, 52,
       52, 52, 48, 48, 48, 48,  1,  0,  1,  0,  0,  0,  1,  1,  0,  0,  0,
        1,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1,  0,  1])

In [21]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, dm.di_7_1760], 
                             [dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_1 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [22]:
HTML(plt_obj.get_html())

In [23]:
sa_64_1575.alleles_per_snp(am_1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, dm.di_7_1868], 
                             [dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_2 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [25]:
HTML(plt_obj.get_html())

In [26]:
sa_64_1575.alleles_per_snp(am_2)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1])

In [27]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, dm.di_24_1504], 
                             [dm.di_7_1868, dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_3 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [28]:
HTML(plt_obj.get_html())

In [29]:
sa_64_1575.alleles_per_snp(am_3)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
di_8_328 = 354064
di_17_137 = 354051
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, di_8_328, di_17_137], 
                             [dm.di_24_1504, dm.di_7_1868, dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_4 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [31]:
HTML(plt_obj.get_html())

In [32]:
sa_64_1575.alleles_per_snp(am_4)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, di_8_328], 
                             [di_17_137, 
                              dm.di_24_1504, dm.di_7_1868, dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_5 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [34]:
HTML(plt_obj.get_html())

In [35]:
sa_64_1575.alleles_per_snp(am_5)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206, dm.di_39_1014], 
                             [di_8_328, 
                              dm.di_24_1504, dm.di_7_1868, dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_6 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [37]:
HTML(plt_obj.get_html())

In [38]:
sa_64_1575.alleles_per_snp(am_6)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_10_2206], 
                             [dm.di_39_1014, di_8_328, 
                              dm.di_24_1504, dm.di_7_1868, dm.di_7_1760, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am_7 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [40]:
HTML(plt_obj.get_html())

In [41]:
sa_64_1575.alleles_per_snp(am_7)

array([49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49, 49, 48, 48, 48, 48, 48, 48, 48, 48, 47, 46, 47,
       47, 47, 47, 47, 47, 47,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [42]:
plt_obj = dm.superset_yes_no([dm.di_4_911], [dm.di_10_2206, dm.di_64_1575, dm.di_11_765], 
                             min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [43]:
di_4_26 = 354116
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_7_1760, di_4_26], 
                             [dm.di_10_2206, dm.di_64_1575, dm.di_11_765],                              
                             min_match=0.001)
plt = plt_obj.do_plot()
am_8 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [44]:
HTML(plt_obj.get_html())

In [45]:
sa_64_1575.alleles_per_snp(am_8)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_7_1760], 
                             [di_4_26, dm.di_10_2206, dm.di_64_1575, dm.di_11_765],                              
                             min_match=0.001)
plt = plt_obj.do_plot()
am_9 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [47]:
HTML(plt_obj.get_html())

In [48]:
sa_64_1575.alleles_per_snp(am_9)

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_4_1442], 
                             [dm.di_7_1760, dm.di_10_2206, dm.di_64_1575, dm.di_11_765],                              
                             min_match=0.001)
plt = plt_obj.do_plot()
am_10 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [50]:
HTML(plt_obj.get_html())

In [51]:
sa_64_1575.alleles_per_snp(am_10)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
plt_obj = dm.superset_yes_no([dm.di_4_911, dm.di_39_1014], 
                             [dm.di_4_1442, dm.di_7_1760, dm.di_10_2206, 
                              dm.di_64_1575, dm.di_11_765],                              
                             min_match=0.001)
plt = plt_obj.do_plot()
am_11 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [53]:
HTML(plt_obj.get_html())

In [54]:
sa_64_1575.alleles_per_snp(am_11)

array([3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
plt_obj = dm.superset_yes_no([dm.di_4_911], 
                             [dm.di_39_1014, dm.di_4_1442, dm.di_7_1760, dm.di_10_2206, 
                              dm.di_64_1575, dm.di_11_765],                              
                             min_match=0.001)
plt = plt_obj.do_plot()
am_12 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [56]:
HTML(plt_obj.get_html())

In [57]:
sa_64_1575.alleles_per_snp(am_12)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])