In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
output_notebook(hide_banner=True)
sa_7_1868 = snp_anal.series_anal_cls(dm.di_7_1868, sm.series_data)
am_7_1868 = dm.allele_mask_from_index(dm.di_7_1868)
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)
am_not_64_1575 = dm.and_and_not_or_allele_mask([dm.di_7_1868], [dm.di_64_1575])

<h3>Series 7_1868</h3>
<div style="width:700px">
<p>
This notebook documents the series 7_1868 and its 7 SNPs.  The 1000 genomes data includes
2929 samples that express none of its 7 SNPs and 1801 samples that express all 7 of them.
Another 67 samples express 6 of them.  There are another 156 samples that express a
4 SNP fragment of 7_1868.  The 7 SNP series covers almost  94,000 DNA bases.  
<p>
The pattern of associations observed for 7_1868 is similar to that observed for 10_2206.
The 29 samples that express 64_1575 but not 7_1868 is a larger number than the 1 sample that
expresses 64_1575 but not 10_2206.  But, it is still a small number that likely reflects
the increased chance for recombination events between the end of 10_2206 and the start
of 7_1868 relative to lower parts of the studied region of chromosome 2.
<p>
The 7_1868 samples include 243 that do not express any 64_1575 SNP's.  The 163 almost
all African samples that express the series 4_163 include 161 that express 7_1868
but not 64_1575.  Those samples include 157 that do not express any 64_1575 SNP's.
Two other series 4_27 and 6_27 almost all expressed by samples from African populations
also are associated with 7_1868 but not 64_1575.  The 54 samples expressing those series
include 53 that do not express any 64_1575 SNP's.
<p>
The 156 samples that express the 4 SNP 7_1868 fragment include all 137 of the samples that
express the 17 SNP series 17_137.
</div>

In [2]:
HTML(dm.series_html(dm.di_7_1868))

In [3]:
count_data = sa_7_1868.unique_snps_per_allele()
count_data

array([(0, 2929), (1, 43), (3, 10), (4, 156), (5, 2), (6, 67), (7, 1801)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [4]:
aps_4, am_4_7_1868 = sa_7_1868.snps_from_aps_value(4)
aps_4

array([  0, 156, 156, 156,   0, 156,   0])

In [5]:
plt_obj = dm.superset_yes_no([dm.di_7_1868, dm.di_64_1575], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [6]:
HTML(plt_obj.get_html())

In [7]:
plt_obj = dm.superset_yes_no([dm.di_7_1868], [dm.di_64_1575], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [8]:
count_data = sa_64_1575.unique_snps_per_allele(am_not_64_1575)
count_data

array([(0, 241), (1, 3), (2, 2), (5, 5), (6, 23), (7, 3), (11, 1), (12, 1),
       (13, 1), (14, 1), (27, 2), (28, 8), (30, 1), (31, 1), (33, 2),
       (35, 1), (37, 1), (39, 1), (40, 1), (42, 1), (43, 15), (44, 2),
       (46, 2), (50, 1), (52, 1), (57, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [9]:
aps_6, am_6 = sa_64_1575.snps_from_aps_value(6, am_not_64_1575)
aps_6

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 23, 23, 23, 23, 23, 23])

In [10]:
aps_28, am_28 = sa_64_1575.snps_from_aps_value(28, am_not_64_1575)
aps_28

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8])

In [11]:
aps_43, am_43 = sa_64_1575.snps_from_aps_value(43, am_not_64_1575)
aps_43

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [12]:
di_4_163 = 354124
plt_obj = dm.superset_yes_no([dm.di_7_1868, di_4_163, dm.di_10_2206], [dm.di_64_1575], min_match=0.5)
plt = plt_obj.do_plot()
am_4_163_10_2206 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
count_data = sa_64_1575.unique_snps_per_allele(am_4_163_10_2206)
count_data

array([(0, 84), (1, 1), (2, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [15]:
plt_obj = dm.superset_yes_no([dm.di_7_1868, di_4_163], [dm.di_10_2206, dm.di_64_1575], min_match=0.5)
plt = plt_obj.do_plot()
am_4_163_not_10_2206 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
count_data = sa_64_1575.unique_snps_per_allele(am_4_163_not_10_2206)
count_data

array([(0, 73), (1, 1), (2, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [18]:
plt_obj = dm.superset_yes_no([dm.di_7_1868], [di_4_163, dm.di_64_1575], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [19]:
di_6_27 =  354101
plt_obj = dm.superset_yes_no([di_6_27],  min_match=0.5)
plt = plt_obj.do_plot()
am_6_27 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
count_data = sa_64_1575.unique_snps_per_allele(am_6_27)
count_data

array([(0, 26), (30, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
di_4_27 =  354042
plt_obj = dm.superset_yes_no([di_4_27],  min_match=0.5)
plt = plt_obj.do_plot()
am_4_27 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
count_data = sa_64_1575.unique_snps_per_allele(am_4_27)
count_data

array([(0, 27)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [25]:
plt_obj = dm.superset_allele_mask(am_4_7_1868, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [26]:
HTML(plt_obj.get_html())