In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
am_26_1414 = dm.allele_mask_from_index(dm.di_26_1414)
am_32_1361 = dm.allele_mask_from_index(dm.di_32_1361)
am_not_26_1414_32_1361 = dm.not_or_allele_mask([dm.di_26_1414, dm.di_32_1361])
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)

<h3>Series 64_1575</h3>
<div style="width:700px">
<p>
This notebook documents the series 64_1575 and its 64 SNPs.  The 1000 genomes data includes
2689 samples that express none of its SNPs and 1369 samples that express all 64 of them.
Another 135 express 63 of them.  Another 415 samples express fragments of the 64 SNPs
that include more than 3 and less than 58 of them.  The 64 SNP series covers an almost 272,000
base region that includes the genes ubxn4, lct, mcm6, and dars. Most of the fragments appear
to have resulted from simple recombination events.
<p>
The data presented in this notebook and others shows that 64_1575, 10_2206, and 7_1818 effectively
are parts of a common series.  All but 1 of the samples that express 64_1575 also express
10_2206.  Only 29 of them fail to express 7_1868.  This notebook primarily explores the expression
of associations that include all three series but not the series 26_1414.  Most of the samples
that express those associations come from East Asian populations.  The sampled chromsomes appear to
have resulted from recombination events that replaced the series 26_1414 with the series 32_1361. 
The samples expressing the resulting association of 32_1361, 64_1575, 10_2206, and 7_1818 along
with other components of the EAS tree appear to have experienced some form of selective advantage 
that has resulted in an large overexpression of them in East Asian populations.  The selective advantage
associated with 64_1575 in a very different context from the EUR tree provides additional evidence
that its overexpression in the EUR tree is not just the chance result of linkage disequilibrium.
</div>

In [2]:
HTML(dm.series_html(dm.di_64_1575))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_64_1575.unique_snps_per_allele()
count_data

array([(0, 2689), (1, 191), (2, 136), (3, 2), (4, 33), (5, 40), (6, 25),
       (7, 4), (9, 7), (10, 1), (11, 17), (12, 1), (13, 1), (14, 1),
       (15, 2), (20, 3), (21, 42), (22, 4), (23, 1), (26, 7), (27, 3),
       (28, 9), (29, 1), (30, 5), (31, 37), (32, 6), (33, 4), (35, 1),
       (36, 12), (37, 6), (39, 2), (40, 50), (41, 8), (42, 1), (43, 15),
       (44, 2), (46, 2), (49, 6), (50, 1), (51, 2), (52, 46), (53, 3),
       (54, 1), (57, 3), (58, 31), (61, 21), (62, 19), (63, 135),
       (64, 1369)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
33+40+25+ 4+7+1+17+1+1+1+ 2+3+42+4+1+7+3 +9+1+5+37+6+4+1 +12+6+2+50+8+1+15 +2+2+6+1+2+46+3 +1+3

415

In [6]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868, dm.di_26_1414], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [7]:
HTML(plt_obj.get_html())

In [8]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868, dm.di_26_1414], [dm.di_6_1503], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [9]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868, dm.di_32_1361], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [10]:
HTML(plt_obj.get_html())

In [11]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868], 
                             [dm.di_26_1414, dm.di_32_1361], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [12]:
plt_obj = dm.superset_yes_no([dm.di_64_1575, dm.di_10_2206, dm.di_7_1868, dm.di_4_1149], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
count_data = sa_64_1575.unique_snps_per_allele(am_26_1414)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [15]:
count_data

array([(0, 10), (1, 11), (2, 1), (20, 2), (21, 38), (22, 4), (23, 1),
       (27, 1), (29, 1), (30, 5), (31, 31), (32, 6), (33, 2), (36, 11),
       (37, 1), (39, 2), (40, 48), (41, 1), (50, 1), (51, 1), (52, 45),
       (53, 2), (57, 2), (58, 20), (61, 20), (62, 11), (63, 79), (64, 1057)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [16]:
aps_61, am_61 = sa_64_1575.snps_from_aps_value(61, am_26_1414)
aps_61

array([20, 20, 20, 20, 20, 20, 20, 20, 20,  1, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,  1, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 19, 20, 20, 19, 20,  1, 20, 20, 19, 20, 20])

In [17]:
plt_obj = dm.superset_allele_mask(am_61, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [18]:
HTML(plt_obj.get_html())

In [19]:
aps_58, am_58 = sa_64_1575.snps_from_aps_value(58, am_26_1414)
aps_58

array([20, 20, 20, 19, 20, 20, 19, 20, 19, 19, 19, 19, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20,  1,  1,  1,  1,  1,  1])

In [20]:
plt_obj = dm.superset_allele_mask(am_58, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
aps_52, am_52 = sa_64_1575.snps_from_aps_value(52, am_26_1414)
aps_52

array([45, 45,  0, 45, 45, 45, 45, 45, 45,  0, 45,  0, 45, 45, 45,  0, 45,
       45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
       45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
       45,  0, 45, 45, 45, 45,  0,  0,  0,  0,  0,  0,  0])

In [23]:
plt_obj = dm.superset_allele_mask(am_52, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [24]:
HTML(plt_obj.get_html())

In [25]:
aps_40, am_40 = sa_64_1575.snps_from_aps_value(40, am_26_1414)
aps_40

array([48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [26]:
plt_obj = dm.superset_allele_mask(am_40, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [27]:
HTML(plt_obj.get_html())

In [28]:
aps_36, am_36 = sa_64_1575.snps_from_aps_value(36, am_26_1414)
aps_36

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [29]:
plt_obj = dm.superset_allele_mask(am_36, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [30]:
HTML(plt_obj.get_html())

In [31]:
aps_32, am_32 = sa_64_1575.snps_from_aps_value(32, am_26_1414)
aps_32

array([6, 6, 4, 6, 6, 6, 6, 6, 6, 4, 6, 4, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
plt_obj = dm.superset_allele_mask(am_32, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [33]:
HTML(plt_obj.get_html())

In [34]:
aps_31, am_31 = sa_64_1575.snps_from_aps_value(31, am_26_1414)
aps_31

array([31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [35]:
plt_obj = dm.superset_allele_mask(am_31, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [36]:
HTML(plt_obj.get_html())

In [37]:
aps_21, am_21 = sa_64_1575.snps_from_aps_value(21, am_26_1414)
aps_21

array([37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
       38, 38, 38, 38,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1])

In [38]:
plt_obj = dm.superset_allele_mask(am_21, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [39]:
HTML(plt_obj.get_html())

In [40]:
count_data = sa_64_1575.unique_snps_per_allele(am_32_1361)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [41]:
count_data

array([(0, 907), (1, 49), (2, 1), (4, 3), (5, 1), (6, 4), (7, 1), (20, 1),
       (21, 1), (27, 1), (28, 1), (31, 1), (36, 1), (37, 4), (40, 1),
       (41, 7), (42, 1), (43, 10), (49, 6), (51, 1), (52, 1), (53, 1),
       (54, 1), (57, 1), (58, 9), (61, 1), (62, 4), (63, 43), (64, 298)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [42]:
aps_58, am_58 = sa_64_1575.snps_from_aps_value(58, am_32_1361)
aps_58

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0])

In [43]:
plt_obj = dm.superset_allele_mask(am_58, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [44]:
HTML(plt_obj.get_html())

In [45]:
aps_49, am_49 = sa_64_1575.snps_from_aps_value(49, am_32_1361)
aps_49

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
plt_obj = dm.superset_allele_mask(am_49, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [47]:
HTML(plt_obj.get_html())

In [48]:
aps_43, am_43 = sa_64_1575.snps_from_aps_value(43, am_32_1361)
aps_43

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [49]:
plt_obj = dm.superset_allele_mask(am_43, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [50]:
HTML(plt_obj.get_html())

In [51]:
count_data = sa_64_1575.unique_snps_per_allele(am_not_26_1414_32_1361)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [52]:
count_data

array([(0, 1772), (1, 131), (2, 134), (3, 2), (4, 30), (5, 39), (6, 21),
       (7, 3), (9, 7), (10, 1), (11, 17), (12, 1), (13, 1), (14, 1),
       (15, 2), (21, 3), (26, 7), (27, 1), (28, 8), (31, 5), (33, 2),
       (35, 1), (37, 1), (40, 1), (43, 5), (44, 2), (46, 2), (58, 2),
       (62, 4), (63, 13), (64, 14)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [53]:
aps_5, am_5 = sa_64_1575.snps_from_aps_value(5, am_not_26_1414_32_1361)
aps_5

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, 35,  0,  0, 35, 35,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 35,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 35,  0,  4,  4,  4,  4,  4])

In [54]:
plt_obj = dm.superset_allele_mask(am_5, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [55]:
HTML(plt_obj.get_html())

In [56]:
aps_4, am_4 = sa_64_1575.snps_from_aps_value(4, am_not_26_1414_32_1361)
aps_4

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        2,  2,  0,  2, 28, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 28,  0,  0,  0,  0,  0,  0])

In [57]:
plt_obj = dm.superset_allele_mask(am_4, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [58]:
HTML(plt_obj.get_html())