In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
di_6_57 = 353444
sa_6_57 = snp_anal.series_anal_cls(di_6_57, sm.series_data)
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)

<h3>Series 6_57</h3>
<div style="width:700px">
<p>
This notebook documents the series 6_57 and its 6 SNPs.  The 1000 genomes data includes
4937 samples that express none of its 6 SNPs and 50 samples that express all 6 of them.
Another 7 samples experss 5 of the SNPs. The 6 SNP series covers more than 493,000 DNA bases.
It is over expressed in European and American populations.  It is not expressed by any samples from East
Asian populations.
<p>
The 57 samples that express 6_57 include 22 that express it in association with all of the
series that are part of the EUR tree root and no other series.  Another 25 samples were derived
from a recombination event that replaced 7_1868 and part of 64_1575 with 39_1014.  This notebook
shows plots for these associations and for those expressed by the other 6_57 samples.
</div>

In [2]:
HTML(dm.series_html(di_6_57))

In [3]:
plt_obj = dm.superset_yes_no([di_6_57], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_6_57.unique_snps_per_allele()
count_data

array([(0, 4937), (1, 3), (2, 2), (3, 2), (4, 7), (5, 7), (6, 50)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206, dm.di_64_1575, dm.di_7_1868], 
                             min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [6]:
HTML(plt_obj.get_html())

In [7]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206, dm.di_64_1575], [dm.di_7_1868], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [8]:
HTML(plt_obj.get_html())

In [9]:
sa_64_1575.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [10]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206, dm.di_39_1014], 
                             [dm.di_64_1575], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [11]:
HTML(plt_obj.get_html())

In [12]:
sa_64_1575.alleles_per_snp(am)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [13]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206, dm.di_24_1504], 
                             [dm.di_39_1014, dm.di_64_1575], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [14]:
HTML(plt_obj.get_html())

In [15]:
sa_64_1575.alleles_per_snp(am)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206, dm.di_7_1868], 
                             [dm.di_24_1504, dm.di_39_1014, dm.di_64_1575], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
sa_64_1575.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [19]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414, dm.di_10_2206], 
                             [dm.di_7_1868, dm.di_24_1504, dm.di_39_1014, dm.di_64_1575], 
                             min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
sa_64_1575.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_26_1414], [dm.di_10_2206], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
sa_64_1575.alleles_per_snp(am)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
plt_obj = dm.superset_yes_no([di_6_57, dm.di_39_1014], [dm.di_26_1414], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [26]:
HTML(plt_obj.get_html())

In [27]:
sa_64_1575.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
plt_obj = dm.superset_yes_no([di_6_57], [dm.di_39_1014, dm.di_26_1414], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [29]:
HTML(plt_obj.get_html())

In [30]:
sa_64_1575.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])