In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_26_1414 = snp_anal.series_anal_cls(dm.di_26_1414, sm.series_data)
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)
sa_5_684 = snp_anal.series_anal_cls(dm.di_5_684, sm.series_data)
sa_9_944 = snp_anal.series_anal_cls(dm.di_9_944, sm.series_data)

<h3>Series 26_1414</h3>
<div style="width:700px">
<p>
This notebook documents the series 26_1414 and its 26 SNPs.  The 1000 genomes data includes
3571 samples that express none of its 26 SNPs and 1302 samples that express all 26 of them.
38 samples express 25 SNPs, 22 samples express 24 SNPs, and 52 samples express 23 SNPs.
The series covers more than a 136,000 DNA base region that includes the the upper part of the 
gene r3hdm1.
<p>
The association between 26_1414 and 6_1503 essentially defines the root of the EUR tree.
That association is expressed by 1270 1000 genomes chromosome 2 samples. This notebook explores 
the associations of 26_1414 that give the series an identity beyond the EUR tree.  
<p>
There are two cases of selection of 26_1414 in African populations.  But both cases select for less
that the full 26 SNPs.  The series 5_16 selects for a 24 SNP series that has lost the first 2 26_1414
SNPs.  The series 14_48 selects for a 23 SNP series that has lost 3 interspersed 26_1414 SNPs
</div>

In [2]:
HTML(dm.series_html(dm.di_26_1414))

In [3]:
count_data = sa_26_1414.unique_snps_per_allele()
count_data

array([(0, 3571), (1, 4), (2, 4), (3, 1), (4, 1), (5, 2), (8, 3), (13, 1),
       (15, 1), (16, 1), (17, 1), (18, 2), (21, 2), (23, 52), (24, 22),
       (25, 38), (26, 1302)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

<div style="width:700px">
<p>
This plot shows the series most commonly associated with 26_1414.  They include the root
of the EUR tree plus the series 4_911 and 11_765.  The 765 chromosomes that express the series
11_765 associated with lactase persisitence are slightly more than half of those that
express 26_1414.  The association of 26_1414 and 6_1503 defines the root of the EUR tree.  The
1270 chromosomes that express this association are 90% of those that express 26_1414.  The strength
of the association between 26_1414 and 10_2206 is stronger then the association of
26_1414 with the EUR tree or with lactase persistence.  The rest of this notebook explores
the associations of 26_1414 outside the EUR tree.
</div>

In [4]:
plt_obj = dm.superset_yes_no([dm.di_26_1414], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [5]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows the most common series for chromosomes that express 26_1414, 4_1699, but not
6_1503.  Most of the plotted associations appear to have resulted from selection by the series
12_32.  The 39 samples in the plot include 30 of the 32 that express 12_32.
</div>

In [6]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_4_1699], [dm.di_6_1503], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [7]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows most common series for samples that express 26_1414 but are
not part of the EUR tree.  The criteria used to identify these samples was
expression of 26_1414 but not 6_1503.  The 144 samples that meet these 
criteria include 81 that express 117_1685.
</div>

In [8]:
plt_obj = dm.superset_yes_no([dm.di_26_1414], [dm.di_6_1503], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [9]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows the most common series for  the 81 samples that express 
26_1414 and 117_1685.  These samples include 51 of the 56 chromosomes
that express the series 209_56.  They also include all 48 of the chromosomes
that express the series 14_48.
</div>

In [10]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_117_1685], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [11]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
The data in this plot shows the most common series for samples that
express the series 14_48.  All 48 of the samples express 117_1685,
26_1414, and 10_2206.  Those samples include 46 that express the series 209_56.
The association of 26_1414 with 10_2206 is the only one in common with the EUR tree.
All 48 of these samples express a 23 SNP subset of the standard 26_1414 SNPs 
and a 52 SNP subset of the 64_1575 SNPs.
</div>

In [12]:
di_14_48 = 353833
plt_obj = dm.superset_yes_no([di_14_48], min_match=0.5)
plt = plt_obj.do_plot()
am_14_48 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
an.sa_26_1414.alleles_per_snp(am_14_48)

array([48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
        0, 48, 48, 48,  0, 48,  0, 48, 48])

In [15]:
sa_64_1575.alleles_per_snp(am_14_48)

array([48, 48,  0, 48, 48, 48, 48, 48, 48,  0, 48,  0, 48, 48, 48,  2, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 47, 48, 48, 48, 48, 48, 48, 48,
       48,  0, 48, 48, 48, 48,  0,  0,  0,  0,  0,  0,  0])

<div style="width:700px">
<p>
This plot shows the most common series for the 33 samples that express
26_1414 and 117_1685 but not 14_48.  The samples include 19 that express
the series 67_329.
</div>

In [16]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_117_1685], [di_14_48], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [17]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows the most common series for the 19 samples that express
26_1414, 117_1685, and 67_329.  Most of the series are expressed by all
19 samples.  One exception is the 1 sample that does not express
7_1868.  The other exception is the series 5_16.  These samples include
14 of the 16 that express 5_16.
</div>

In [18]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_117_1685, dm.di_67_329], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [19]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows the most common series for the 16 samples that express
the series 5_16. All 16 of these samples express 26_1414, 10_2206, 64_1575, and
7_1868.
</div>

In [20]:
di_5_16 = 353821
plt_obj = dm.superset_yes_no([di_5_16], min_match=0.5)
plt = plt_obj.do_plot()
am_5_16 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
an.sa_26_1414.alleles_per_snp(am_5_16)

array([ 0,  0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16])

In [23]:
plt_obj = dm.superset_yes_no([di_5_16], [dm.di_117_1685], min_match=0.5)
plt = plt_obj.do_plot()
am_180_251_26_1414 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [24]:
HTML(plt_obj.get_html())

In [25]:
sa_180_251 = snp_anal.series_anal_cls(dm.di_180_251, sm.series_data)
sa_180_251.alleles_per_snp(am_180_251_26_1414)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
an.sa_26_1414.alleles_per_snp(am_180_251_26_1414)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

<div style="width:700px">
<p>
This plot shows the most common series for the 20 samples that express
26_1414 and 13_1696.  All 20 also express 10_2206, 64_1575, and 7_1868.
The next serveral plots show the varied associations of other series with
this common set.
</div>

In [27]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [28]:
HTML(plt_obj.get_html())

In [29]:
sa_26_1414.alleles_per_snp(am)

array([18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20])

In [30]:
sa_9_944.alleles_per_snp(am)

array([14, 14, 14, 14, 13, 13,  0,  0,  0])

In [31]:
sa_5_684.alleles_per_snp(am)

array([11, 10, 10, 10,  9])

In [32]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, dm.di_123_1561, dm.di_180_251], [dm.di_5_588], min_match=0.5)
plt = plt_obj.do_plot()
am_180_251_26_1414_not_5_588 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [33]:
HTML(plt_obj.get_html())

In [34]:
sa_180_251 = snp_anal.series_anal_cls(dm.di_180_251, sm.series_data)
sa_180_251.alleles_per_snp(am_180_251_26_1414_not_5_588)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
an.sa_26_1414.alleles_per_snp(am_180_251_26_1414_not_5_588)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [36]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, dm.di_123_1561], [dm.di_180_251], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [37]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows data for 2 samples that have exprienced recombination events
that left 13_1696 associated with 6_1503 and other series from the EUR tree.
The 1000 genome data appears not to include any samples that express 13_1696,
4_1699, and 26_1414 without 6_1503.  Given the subtantial number of samples
that do express 13_1696 and 4_1699 without 6_1503, this result seems to indicate
some kind of negative selection for that association.
</div>

In [38]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, dm.di_4_1699], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [39]:
HTML(plt_obj.get_html())

<div style="width:700px">
<p>
This plot shows data for the 15 samples that express 26_1414 and
13_1696 but not 123_1561 or 4_1699.  These samples include 9 that
express 5_684.  The following plot shows the data for those 9 samples.
</div>

In [40]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696], [dm.di_123_1561, dm.di_4_1699], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [41]:
HTML(plt_obj.get_html())

In [42]:
sa_26_1414.alleles_per_snp(am)

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15])

In [43]:
sa_9_944.alleles_per_snp(am)

array([14, 14, 14, 14, 13, 13,  0,  0,  0])

In [44]:
sa_5_684.alleles_per_snp(am)

array([11, 10, 10, 10,  9])

In [45]:
di_4_37 = 353635
di_4_34 = 353308
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, dm.di_5_684], 
                             [di_4_34, di_4_37, dm.di_123_1561, dm.di_4_1699], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [46]:
HTML(plt_obj.get_html())

In [47]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, dm.di_5_684, di_4_34, di_4_37],
                             [dm.di_123_1561, dm.di_4_1699], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [48]:
HTML(plt_obj.get_html())

In [49]:
sa_26_1414.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [50]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 0, 0, 0])

In [51]:
sa_5_684.alleles_per_snp(am)

array([1, 1, 1, 1, 1])

<div style="width:700px">
<p>
This plot and the following ones show data for the remaining 6 samples that
express 26_1414 and 13_1696.
</div>

In [52]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696], 
                             [dm.di_5_684, dm.di_123_1561, dm.di_4_1699], min_match=0.1)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [53]:
HTML(plt_obj.get_html())

In [54]:
sa_26_1414.alleles_per_snp(am)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6])

In [55]:
sa_9_944.alleles_per_snp(am)

array([5, 5, 5, 5, 4, 4, 0, 0, 0])

In [56]:
sa_5_684.alleles_per_snp(am)

array([2, 1, 1, 1, 0])

In [57]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, di_4_37], 
                             [dm.di_5_684, dm.di_123_1561, dm.di_4_1699], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [58]:
HTML(plt_obj.get_html())

In [59]:
sa_26_1414.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [60]:
sa_9_944.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 0, 0, 0])

In [61]:
sa_5_684.alleles_per_snp(am)

array([1, 1, 1, 1, 0])

In [62]:
di_7_20 = 353570
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696, di_7_20], 
                             [dm.di_5_684, dm.di_123_1561, dm.di_4_1699], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [63]:
HTML(plt_obj.get_html())

In [64]:
sa_26_1414.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [65]:
sa_9_944.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
sa_5_684.alleles_per_snp(am)

array([0, 0, 0, 0, 0])

In [67]:
plt_obj = dm.superset_yes_no([dm.di_26_1414, dm.di_13_1696], 
                             [di_7_20, di_4_37, dm.di_5_684, dm.di_123_1561, dm.di_4_1699], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [68]:
HTML(plt_obj.get_html())

In [69]:
sa_26_1414.alleles_per_snp(am)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4])

In [70]:
sa_9_944.alleles_per_snp(am)

array([4, 4, 4, 4, 3, 3, 0, 0, 0])

In [71]:
sa_5_684.alleles_per_snp(am)

array([1, 0, 0, 0, 0])

In [72]:
count_data = an.sa_26_1414.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [73]:
count_data

array([(0, 3571), (1, 4), (2, 4), (3, 1), (4, 1), (5, 2), (8, 3), (13, 1),
       (15, 1), (16, 1), (17, 1), (18, 2), (21, 2), (23, 52), (24, 22),
       (25, 38), (26, 1302)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [74]:
aps_23, am_23 = an.sa_26_1414.snps_from_aps_value(23)
aps_23

array([52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
        0, 52, 52, 52,  0, 52,  0, 52, 52])

In [75]:
aps_24, am_24 = an.sa_26_1414.snps_from_aps_value(24)
aps_24

array([ 1,  1, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 21, 21])