In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
di_6_35 = 353407
sa_6_35 = snp_anal.series_anal_cls(di_6_35, sm.series_data)
sa_64_1575 = snp_anal.series_anal_cls(dm.di_64_1575, sm.series_data)

<h3>Series 6_35</h3>
<div style="width:700px">
<p>
This notebook documents the series 6_35 and its 6 SNPs.  The 1000 genomes data includes
4965 samples that express none of its 6 SNPs and 35 samples that express all 6 of them.
The 6 SNP series covers almost  122,000 DNA bases.  The series 6_35 is over expressed
in American and European populations.  It is not expressed by any samples from East
Asian populations.
<p>
The 35 samples that express 6_35 include 29 that express it in association with all of the
series that are part of the EUR tree root and no other series.
<p>
This notebook shows the recombination event generated series associations expressed by the
other 6 samples.
</div>

In [2]:
HTML(dm.series_html(di_6_35))

In [3]:
plt_obj = dm.superset_yes_no([di_6_35], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_6_35.unique_snps_per_allele()
count_data

array([(0, 4965), (2, 2), (3, 6), (6, 35)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
plt_obj = dm.superset_yes_no([di_6_35, dm.di_10_2206, dm.di_7_1868], [dm.di_4_911], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [6]:
HTML(plt_obj.get_html())

In [7]:
plt_obj = dm.superset_yes_no([di_6_35, dm.di_10_2206, dm.di_7_1868, dm.di_4_911], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [8]:
HTML(plt_obj.get_html())

In [9]:
plt_obj = dm.superset_yes_no([di_6_35, dm.di_10_2206, dm.di_39_1014], [dm.di_7_1868], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [10]:
HTML(plt_obj.get_html())

In [11]:
sa_64_1575.alleles_per_snp(am)

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [12]:
plt_obj = dm.superset_yes_no([di_6_35, dm.di_10_2206, dm.di_64_1575], [dm.di_7_1868], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
sa_64_1575.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [15]:
plt_obj = dm.superset_yes_no([di_6_35, dm.di_10_2206], [dm.di_64_1575,dm.di_39_1014, dm.di_7_1868], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
sa_64_1575.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
plt_obj = dm.superset_yes_no([di_6_35], [dm.di_10_2206], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
sa_64_1575.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])