In [87]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_8_267 = snp_anal.series_anal_cls(dm.di_8_267, sm.series_data)
sa_8_267 = snp_anal.series_anal_cls(dm.di_8_267, sm.series_data)
am_8_267 = dm.allele_mask_from_index(dm.di_8_267)
sa_32_1361 = snp_anal.series_anal_cls(dm.di_32_1361, sm.series_data)
sa_26_1414 = snp_anal.series_anal_cls(dm.di_32_1361, sm.series_data)

<h3>Series 8_267</h3>
<div style="width:700px">
<p>
This notebook documents the series 8_267 and its 8 SNPs.  The 1000 genomes data includes
4688 samples that express none of its 8 SNPs and 259 samples that express all 8 of them.
Another 8 samples express 7 of the SNPs. The 8 SNP series covers more than 471,000 DNA bases.
It is overexpressed in American, European, and South Asian populations.  It is under expressed
in African populations.
<p>
The series 8_267 is a child of 6_713.  All 267 samples express 6_713.  264 of them express 4_815.
But, only 223 samples express 193_843.  The main reason is the history of a recombination event
shared by 41 of the 8_267 samples.  That recombination event caused the loss of the top 23
193_843 SNPs.  38 of the 8_267 samples have resulted from this recombination event and the selection
process associated with the appearance of the series 9_39.
<p>
The descendant series of 8_267 are 5_16, 5_26, 9_39, and 4_45.  There are 143 samples that express
8_267 but none of its descendants.  Those samples include 66 that express all the standard series
of the SAS tree root including 39_1014 along with 5_976 and 6_820.  Another 39 express the same
hierarchy without 5_976 or 6_820.  The other samples show an history of a variety of recombination
events.  3 show the an history of the event associated with 9_39 where recombination with a chromosome
containing 32_1361 and 81_857 replaced the top SNPs in 193_843.  2 show an history of a recombination
event where 13_1696 replaced the lower part of 193_843.
</div>

In [2]:
HTML(dm.series_html(dm.di_8_267))

In [3]:
count_data = sa_8_267.unique_snps_per_allele()
count_data

array([(0, 4688), (1, 31), (2, 3), (3, 2), (5, 12), (6, 5), (7, 8),
       (8, 259)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [4]:
plt_obj = dm.superset_yes_no([dm.di_8_267], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [5]:
HTML(plt_obj.get_html())

In [6]:
count_data = an.sa_193_843.unique_snps_per_allele(am_8_267)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(165, 2), (169, 1), (170, 41), (191, 1), (192, 26), (193, 196)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
spa_170, am_170 = an.sa_193_843.snps_from_aps_value(170, am_8_267)
spa_170

array([41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [9]:
plt_obj = dm.superset_allele_mask(am_170, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [10]:
HTML(plt_obj.get_html())

In [17]:
di_5_16 = 353456
di_5_26 = 353468
di_9_39 = 353559
di_4_45 = 353626
plt_obj = dm.superset_yes_no([dm.di_8_267], [di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [18]:
di_4_49 = 353811
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014, dm.di_5_1460, dm.di_117_1685, dm.di_5_976],
                             [di_4_49,
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
di_4_49 = 353811
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014, dm.di_5_1460, dm.di_117_1685, dm.di_5_976,
                              di_4_49],
                             [di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014, dm.di_5_1460, dm.di_117_1685], 
                             [dm.di_5_976, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [66]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014, dm.di_5_1460], 
                             [dm.di_117_1685, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [67]:
HTML(plt_obj.get_html())

In [68]:
an.sa_193_843.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014, dm.di_123_1561], 
                             [dm.di_5_1460, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [27]:
HTML(plt_obj.get_html())

In [69]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_39_1014], 
                             [dm.di_123_1561, dm.di_5_1460, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [70]:
HTML(plt_obj.get_html())

In [71]:
an.sa_193_843.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_4_1442, dm.di_7_1760, dm.di_9_1170], 
                             [dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [31]:
HTML(plt_obj.get_html())

In [32]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_4_1442, dm.di_7_1760], 
                             [dm.di_9_1170, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [33]:
HTML(plt_obj.get_html())

In [34]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_4_1442, dm.di_24_1504, dm.di_51_176], 
                             [dm.di_7_1760, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [35]:
HTML(plt_obj.get_html())

In [36]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_4_1442, dm.di_24_1504], 
                             [dm.di_51_176, dm.di_7_1760, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [37]:
HTML(plt_obj.get_html())

In [38]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_4_1442], 
                             [dm.di_24_1504, dm.di_7_1760, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [39]:
HTML(plt_obj.get_html())

In [40]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_64_1575], 
                             [dm.di_4_1442, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [41]:
HTML(plt_obj.get_html())

In [42]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_9_1170], 
                             [dm.di_64_1575, dm.di_4_1442, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [43]:
HTML(plt_obj.get_html())

In [44]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_5_976, dm.di_7_1760], 
                             [dm.di_9_1170, 
                              dm.di_64_1575, dm.di_4_1442, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [45]:
HTML(plt_obj.get_html())

In [46]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460, dm.di_5_976], 
                             [dm.di_7_1760, dm.di_9_1170, 
                              dm.di_64_1575, dm.di_4_1442, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [47]:
HTML(plt_obj.get_html())

In [48]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_5_1460], 
                             [dm.di_5_976, dm.di_9_1170, 
                              dm.di_64_1575, dm.di_4_1442, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [49]:
HTML(plt_obj.get_html())

In [72]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_32_1361, dm.di_10_2206], 
                             [dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [73]:
HTML(plt_obj.get_html())

In [74]:
an.sa_193_843.alleles_per_snp(am)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4])

In [76]:
sa_32_1361.alleles_per_snp(am)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4])

In [79]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_32_1361, dm.di_123_1561], 
                             [dm.di_10_2206, dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [80]:
HTML(plt_obj.get_html())

In [81]:
an.sa_193_843.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [82]:
sa_32_1361.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [83]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_32_1361], 
                             [dm.di_123_1561, 
                              dm.di_10_2206, dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [84]:
HTML(plt_obj.get_html())

In [85]:
an.sa_193_843.alleles_per_snp(am)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
sa_32_1361.alleles_per_snp(am)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [56]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_51_176], 
                             [dm.di_32_1361, dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [57]:
HTML(plt_obj.get_html())

In [88]:
plt_obj = dm.superset_yes_no([dm.di_8_267, dm.di_10_2206], 
                             [dm.di_51_176, dm.di_32_1361, dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [89]:
HTML(plt_obj.get_html())

In [90]:
sa_26_1414.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
plt_obj = dm.superset_yes_no([dm.di_8_267], 
                             [dm.di_10_2206, 
                              dm.di_51_176, dm.di_32_1361, dm.di_5_1460, dm.di_39_1014, 
                              di_5_16, di_5_26, di_9_39, di_4_45], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [61]:
HTML(plt_obj.get_html())