In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
sa_29_68 = snp_anal.series_anal_cls(dm.di_29_68, sm.series_data)
am_29_68 = dm.allele_mask_from_index(dm.di_29_68)

<h3>Series 29_68</h3>
<div style="width:700px">
<p>
This notebook documents the series 29_68 and its 29 SNPs.  The 1000 genomes data includes
4922 samples that express none of its 29 SNPs and 63 samples that express all 29 of them.
Another 2 samples express 28 of the SNPs. The 29 SNP series covers almost 611,000 DNA bases.
It is over expressed in South Asian populations.
<p>
The series 29_68 is a direct child of 193_843.  It is the root of an hierarchy that includes
the series 10_25, 6_19, and 8_17.  There are 11 samples that express 29_68 and none of its
descendant series.  Those 11 samples all express 193_843, 62_1265, 123_1561, and 117_1685.
But, the associated series in the higher parts of the region are not the common ones of the
SAS tree.  7 of the samples express 32_1361.  10 express 10_2206.  But, none express 64_1575
or 81_857.
</div>

In [2]:
HTML(dm.series_html(dm.di_29_68))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_29_68], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
plt_obj = dm.superset_yes_no([dm.di_29_68], min_match=0.5)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [5]:
count_data = sa_29_68.unique_snps_per_allele()
count_data

array([(0, 4922), (1, 7), (3, 2), (4, 1), (6, 4), (20, 1), (21, 2),
       (25, 1), (26, 1), (27, 2), (28, 2), (29, 63)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
an.sa_117_1685.unique_snps_per_allele(am_29_68)

array([(116, 68)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
an.sa_117_1685.alleles_per_snp(am_29_68)

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,  0, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68])

In [8]:
an.sa_123_1561.unique_snps_per_allele(am_29_68)

array([(123, 68)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [9]:
an.sa_62_1265.unique_snps_per_allele(am_29_68)

array([(59, 2), (60, 34), (62, 32)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
aps_60, am_60 = an.sa_62_1265.snps_from_aps_value(60, am_29_68)
aps_60

array([34, 34, 34,  0,  0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34])

In [11]:
an.sa_193_843.unique_snps_per_allele(am_29_68)

array([(191, 2), (192, 55), (193, 11)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [12]:
aps_192, am_192 = an.sa_193_843.snps_from_aps_value(192, am_29_68)
aps_192

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 12,
       55, 55, 55, 55, 55, 55, 43, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 55])

In [13]:
di_10_25 = 353386
di_6_19 = 353568
di_8_17 = 353548
subs = [di_10_25, di_6_19, di_8_17]
plt_obj = dm.superset_yes_no([dm.di_29_68], subs, min_match=0.001)
plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [14]:
plt_obj = dm.superset_yes_no([dm.di_29_68, dm.di_32_1361, dm.di_24_1504], subs, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [15]:
HTML(plt_obj.get_html())

In [16]:
noi = [dm.di_24_1504]
noi.extend(subs)
plt_obj = dm.superset_yes_no([dm.di_29_68, dm.di_32_1361, dm.di_10_2206], noi, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
noi = [dm.di_24_1504, dm.di_10_2206]
noi.extend(subs)
plt_obj = dm.superset_yes_no([dm.di_29_68, dm.di_32_1361], noi, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
noi = [dm.di_32_1361]
noi.extend(subs)
plt_obj = dm.superset_yes_no([dm.di_29_68, dm.di_5_1460, dm.di_39_1014], noi, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
noi = [dm.di_32_1361, dm.di_39_1014]
noi.extend(subs)
plt_obj = dm.superset_yes_no([dm.di_29_68, dm.di_5_1460], noi, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
noi = [dm.di_32_1361, dm.di_5_1460]
noi.extend(subs)
plt_obj = dm.superset_yes_no([dm.di_29_68], noi, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [25]:
HTML(plt_obj.get_html())