In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
sa_39_1014 = snp_anal.series_anal_cls(dm.di_39_1014, sm.series_data)

<h3>Series 39_1014</h3>
<div style="width:700px">
<p>
This notebook documents the series 39_1014 and its 39 SNPs.  The 1000 genomes data includes
3160 samples that express none of its 39 SNPs and 935 samples that express all 39 of them.
Another 72 samples express 38 of the SNPs. The 39 SNP series covers more than 190,000 DNA bases
in a similar upper part of the studied region as 64_1575 and 81_857.  It is modestly over
expressed in South Asian and American populations.  But, it is substantially expressed in
all of the 1000 genomes populations.
<p>
Six selection processes have been identified that contributed to the overexpression of
39_1014.  The most significant one was the emergence of the SAS tree.  The 843 samples
that express hierarchies that form the SAS tree include 518 that express 39_1014.
<p>
A second independent selection process was the one that generated the hierarchies associated
with the series 74_210.  The 210 samples that express 74_210 include 167 that express
39_1014.
<p>
A third independent selection process was the one that generated the series 6_88.  That
series emerged in the hiearchy that includes 28_434, 180_251, 123_1561, and 13_1696.
The 88 samples that express 6_88 include 48 that express 39_1014.
<p>
A fourth independent selection process was the one that generated the series 5_40.  That
series emerged in an hierarchy that includes 13_1696, 5_1460, 10_1218, and 4_1129. The
40 samples that express 5_40 include 27 that express 39_1014.
<p>
A fifth independent selection process was the one that generated the series 9_27.  That
series emerged in the same part of chromosome 2 as 39_1014.  All 27 samples that express
9_27 also express 39_1014.  Those samples include 16 that express the series 219_26.  There
appears to be some connection between the selection processes that generated these series
across the whole studied region.
<p>
A sixth independent selection process was the one that generated the series 4_17.  All
17 samples that express 4_17 also express 39_1014.  Those samples include 10 that express
290_16.  This process appears to have been another one that generated a complex series
that covered the whole studied region.
<p>
Another 219 samples express 39_1014.  The hiearchies expressed by these samples seem to
result from a variety of recombination events without any obvious selecting series.
<p>
Another 525 samples express fragments of 39_1014 that are more than 3 SNPs and less than
34.  There is a substantial variation to the SNPs involved in the fragments that has
not been completely sorted out.  But most of them appear to have resulted from recombination
events where either a sequence of early or late SNPs was lost.
</div>

In [2]:
HTML(dm.series_html(dm.di_39_1014))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_39_1014], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_39_1014.unique_snps_per_allele()
count_data

array([(0, 3160), (1, 276), (2, 32), (3, 1), (5, 7), (11, 49), (12, 130),
       (13, 65), (14, 34), (15, 1), (18, 4), (19, 1), (21, 5), (22, 58),
       (24, 1), (25, 18), (26, 76), (27, 49), (28, 22), (29, 1), (33, 2),
       (34, 2), (36, 1), (37, 6), (38, 72), (39, 935)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
7+49+130 +65+34+1+4+1+5+58 +1+18+76+49+22+1+2+2

525

In [6]:
aps_11, am_11 = sa_39_1014.snps_from_aps_value(11)
aps_11

array([ 4, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  6,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 38, 38, 39,  1, 39, 39, 39, 39,
        1, 39, 39, 39, 39])

In [7]:
aps_12, am_12 = sa_39_1014.snps_from_aps_value(12)
aps_12

array([63, 63, 63, 63, 64, 63, 63, 63, 63, 63, 63, 63,  0,  0,  0,  0,  0,
        0,  0,  0,  8,  0,  8,  0,  8,  0, 12, 67, 59, 58, 67, 67, 67, 67,
       58, 64, 59, 67, 67])

In [8]:
aps_13, am_13 = sa_39_1014.snps_from_aps_value(13)
aps_13

array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  4,  2,  2,
        2,  3,  2,  2,  2,  2,  2,  2, 29, 57, 61, 61, 61, 61, 61, 61, 61,
       62, 34, 61, 61, 61])

In [9]:
aps_14, am_14 = sa_39_1014.snps_from_aps_value(14)
aps_14

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,  4,  5,
        4,  4,  4,  4,  4,  4,  4,  4, 33, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30])

In [10]:
aps_22, am_22 = sa_39_1014.snps_from_aps_value(22)
aps_22

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
       58, 58, 58, 58, 58])

In [11]:
aps_26, am_26 = sa_39_1014.snps_from_aps_value(26)
aps_26

array([76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
       76, 76, 76, 76, 76, 76, 76, 76, 68,  7,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0])

In [12]:
aps_27, am_27 = sa_39_1014.snps_from_aps_value(27)
aps_27

array([ 6,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0, 43, 49, 43, 49, 49,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
       49, 49, 49, 49, 49])

In [13]:
aps_28, am_28 = sa_39_1014.snps_from_aps_value(28)
aps_28

array([22, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 22, 22, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 22, 22, 22, 22,  7,  2,  2,  2,  2,  2,  2,
       17,  2,  2,  2,  2])

In [14]:
plt_obj = dm.superset_yes_no([dm.di_193_843], min_match=0.5)
plt = plt_obj.do_plot()
am_193_843 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [15]:
HTML(plt_obj.get_html())

In [16]:
plt_obj = dm.superset_yes_no([dm.di_74_210], min_match=0.5)
plt = plt_obj.do_plot()
am_74_210 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [17]:
HTML(plt_obj.get_html())

In [18]:
sa_39_1014.unique_snps_per_allele(am_74_210)

array([(0, 19), (1, 2), (14, 2), (21, 1), (24, 1), (26, 4), (28, 13),
       (33, 1), (38, 9), (39, 158)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [19]:
di_6_88 = 353415
plt_obj = dm.superset_yes_no([di_6_88], min_match=0.5)
plt = plt_obj.do_plot()
am_6_88 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
sa_39_1014.unique_snps_per_allele(am_6_88)

array([(0, 8), (12, 18), (13, 1), (25, 8), (26, 5), (39, 48)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
di_5_40 = 353536
plt_obj = dm.superset_yes_no([di_5_40], min_match=0.5)
plt = plt_obj.do_plot()
am_5_40 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
sa_39_1014.unique_snps_per_allele(am_5_40)

array([(0, 1), (12, 9), (13, 3), (38, 1), (39, 26)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [25]:
di_9_27 = 353975
plt_obj = dm.superset_yes_no([di_9_27], min_match=0.5)
plt = plt_obj.do_plot()
am_9_27 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [26]:
HTML(plt_obj.get_html())

In [27]:
sa_39_1014.unique_snps_per_allele(am_9_27)

array([(38, 1), (39, 26)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [28]:
di_4_17 = 353922
plt_obj = dm.superset_yes_no([di_4_17], min_match=0.5)
plt = plt_obj.do_plot()
am_4_17 = plt_obj.plot_context.yes_allele_mask
show(plt)

In [29]:
HTML(plt_obj.get_html())

In [30]:
sa_39_1014.unique_snps_per_allele(am_4_17)

array([(37, 1), (38, 4), (39, 12)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [31]:
plt_obj = dm.superset_yes_no([dm.di_39_1014], 
                             [dm.di_193_843, dm.di_74_210, di_6_88, di_5_40, di_9_27, di_4_17], min_match=0.001)
plt_obj.do_plot()
am_back = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [32]:
sa_39_1014.unique_snps_per_allele(am_back)

array([(38, 16), (39, 203)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])