In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
from genomes_dnj.lct_interval.series_masks import am_193_843

<h3>Series 193_843</h3>
<div style="width:700px">
<p>
This notebook documents the series 193_843 and its 193 SNPs.  The 1000 genomes data includes
3458 samples that express none of its SNPs and 696 samples that express all 193 of them.
Another 120 samples express 192 of the SNPs. The 193 SNP series covers more than 628,000 DNA bases.
It is most over expressed in South Asian populations, modestly overexpressed in American populations,
average in East Asian populations and modestly underexpressed in African and European populations.
All 843 samples express 62_1265 and 123_1561.  842 of them express 117_685.
<p>
Another 321 samples express fragments of 193_843 more than 4 and less than 182 SNPs.  This notebook
explores the series associated with the four fragments expressed by large numbers of samples.
<p>
A 12 SNP fragment is expressed by 39 samples.  Those samples include 38 that were selected by the
series 147_38.  These samples all come from African populations.
<p>
94 samples express 29 SNP fragments. There are two different fragments.  One includes the first 29
SNPs of series 193_843 and is expressed by 93 samples.  All of these samples express the series 8_415.
Most of them express an association that includes 5_684, 32_1361, 64_1575, 10_2206, and 7_1868.  The
other sample expresses a fragment of 29 SNPs that are spread over the 193 SNP series.  It also expresses
123_1561 and 117_1685.
<p>
A 55 SNP fragment is expressed by 27 samples.  It was selected by the series 25_27 in the hierarchy
selected by 28_434 that expresses both 123_1561 and 117_1685.
<p>
A 170 SNP fragment is expressed by 41 samples.  This fragment has resulted from a recombination event
of the series 8_267 and selection by the series 9_39.
<p>
Only 16 samples express 193_843 without any of its descendant series in the SAS tree.  The hierarchies
expressed by these samples are explored in this notebook
</div>

In [2]:
HTML(dm.series_html(dm.di_193_843))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_193_843], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [4]:
HTML(plt_obj.get_html())

In [5]:
count_data = an.sa_193_843.unique_snps_per_allele()
count_data

array([(0, 3458), (1, 215), (2, 174), (3, 2), (4, 3), (5, 52), (6, 8),
       (7, 3), (8, 2), (9, 1), (10, 1), (11, 1), (12, 39), (15, 1),
       (17, 1), (18, 3), (19, 1), (21, 1), (23, 3), (26, 1), (27, 1),
       (28, 12), (29, 94), (30, 1), (44, 2), (54, 1), (55, 27), (63, 2),
       (65, 2), (98, 1), (100, 1), (101, 1), (139, 1), (158, 1), (164, 3),
       (165, 3), (169, 1), (170, 41), (174, 4), (175, 1), (181, 3),
       (185, 1), (186, 1), (188, 2), (191, 15), (192, 120), (193, 696)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
52+8 +3+2+1+1+1+39+1 +1+3+1+1+3+1+1 +12+94+1+2+1+27+2 +2+1+1+1+1+1+3 +3+1+41+4+1+3 

321

In [7]:
aps_12, am_12 = an.sa_193_843.snps_from_aps_value(12)
aps_12

array([39,  0,  0,  0, 39,  0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 39,
        0, 39,  0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, 39, 39,  0,  0,  0,  0,  0,  0,  0, 39,  0,  0,  0,  0,  0,
        0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0, 39,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 39,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [8]:
plt_obj = dm.superset_allele_mask(am_12, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [9]:
HTML(plt_obj.get_html())

In [10]:
aps_29, am_29 = an.sa_193_843.snps_from_aps_value(29)
aps_29

array([93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93,
       93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  1,  0,  0,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  1,  1,  1,  0,  0,
        0,  0,  1,  0,  1,  0,  0,  0,  0,  1,  0,  1,  0,  0,  1,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  1,
        1,  0,  0,  1,  0,  0,  1,  0,  1,  0,  1,  1,  0,  0,  1,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [11]:
am_4_815 = dm.yes_allele_mask_and_indexes(am_29, [dm.di_4_815])
am_not_4_815 = dm.yes_allele_mask_not_or_indexes(am_29, [dm.di_4_815])

In [12]:
plt_obj = dm.superset_allele_mask(am_4_815, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [13]:
HTML(plt_obj.get_html())

In [14]:
an.sa_193_843.alleles_per_snp(am)

array([93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93,
       93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [15]:
plt_obj = dm.superset_allele_mask(am_not_4_815, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
an.sa_193_843.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
aps_55, am_55 = an.sa_193_843.snps_from_aps_value(55)
aps_55

array([27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  0, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
        0, 27, 27,  0,  0,  0, 27, 27,  0, 27,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [19]:
plt_obj = dm.superset_allele_mask(am_55, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
aps_170, am_170 = an.sa_193_843.snps_from_aps_value(170)
aps_170

array([41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [22]:
plt_obj = dm.superset_allele_mask(am_170, min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [23]:
HTML(plt_obj.get_html())

In [24]:
count_data = an.sa_117_1685.unique_snps_per_allele(am_193_843)
count_data

array([(70, 1), (109, 1), (113, 7), (114, 3), (115, 26), (116, 103),
       (117, 702)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [25]:
count_data = an.sa_123_1561.unique_snps_per_allele(am_193_843)
count_data

array([(113, 3), (116, 1), (120, 1), (121, 5), (122, 104), (123, 729)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
count_data = an.sa_62_1265.unique_snps_per_allele(am_193_843)
count_data

array([(59, 3), (60, 45), (61, 12), (62, 783)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [27]:
di_7_90 = 353285
di_14_57 = 353355
di_29_68 = 353292
di_4_91 = 353320
di_7_79 = 353396
di_14_39 = 353262
di_9_29 = 353413
di_6_43 = 353437
di_4_49 = 353811
di_5_16 = 353456
di_5_26 = 353468
di_9_39 = 353559
di_4_45 = 353626
child_series = [dm.di_6_713, di_7_90, di_14_57, di_29_68, 
              dm.di_4_416, di_4_91, di_7_79, di_14_39, di_9_29, di_6_43, di_4_49, 
              dm.di_8_267, di_5_16, di_5_26, di_9_39, di_4_45]

plt_obj = dm.superset_yes_no([dm.di_193_843], child_series,  min_match=0.001)
plt_obj.do_plot()
am_not = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [28]:
an.sa_117_1685.unique_snps_per_allele(am_not)

array([(116, 3), (117, 13)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [29]:
an.sa_123_1561.unique_snps_per_allele(am_not)

array([(122, 6), (123, 10)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [30]:
an.sa_62_1265.unique_snps_per_allele(am_not)

array([(60, 6), (62, 10)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [31]:
an.sa_193_843.unique_snps_per_allele(am_not)

array([(174, 4), (175, 1), (191, 2), (192, 6), (193, 3)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [32]:
plt_obj = dm.superset_yes_no([dm.di_193_843, dm.di_10_2206, dm.di_5_1460], child_series,  min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [33]:
HTML(plt_obj.get_html())

In [34]:
not_series = [dm.di_5_1460]
not_series.extend(child_series)
plt_obj = dm.superset_yes_no([dm.di_193_843, dm.di_10_2206], not_series,  min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [35]:
HTML(plt_obj.get_html())

In [36]:
not_series = [dm.di_10_2206]
not_series.extend(child_series)
plt_obj = dm.superset_yes_no([dm.di_193_843, dm.di_5_1460], not_series,  min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [37]:
HTML(plt_obj.get_html())

In [38]:
not_series = [dm.di_10_2206, dm.di_5_1460]
not_series.extend(child_series)
plt_obj = dm.superset_yes_no([dm.di_193_843, dm.di_117_1685, dm.di_4_815], not_series,  min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [39]:
HTML(plt_obj.get_html())

In [40]:
not_series = [dm.di_10_2206, dm.di_5_1460, dm.di_4_815]
not_series.extend(child_series)
plt_obj = dm.superset_yes_no([dm.di_193_843, dm.di_117_1685], not_series,  min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [41]:
HTML(plt_obj.get_html())