In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
di_14_57 = 353355
sa_14_57 = snp_anal.series_anal_cls(di_14_57, sm.series_data)
am_14_57 = dm.allele_mask_from_index(di_14_57)
sa_7_90 = snp_anal.series_anal_cls(dm.di_7_90, sm.series_data)

<h3>Series 14_57</h3>
<div style="width:700px">
<p>
This notebook documents the series 14_57 and its 14 SNPs.  The 1000 genomes data includes
4941 samples that express none of its 14 SNPs and 55 samples that express all 14 of them.
Another 2 samples express 13 of the SNPs. The 14 SNP series covers more than 710,000 DNA bases.
It is over expressed in South Asian populations.  It is not expressed by any samples from
Africa, America, or Europe.
<p>
14_57 is a child of the series 7_90.  It is part of the SAS tree hierarchy that does not express
6_713 or 4_815.  But, all 57 samples do express 193_843, 62_1265, and 123_1561.  56 of them express
117_1685 and 7_90.  1 sample expresses an hiearchy that resulted from a recombination event where
early SNPs from 117_1685, 62_1265, 193_843, and 7_90 were lost.  None of the 57 samples express
more than 122 of the 123_1561 SNPs.
<p>
The series 14_57 extends into the region of chromsome 2 where the upper part of the gene r3hdm1
and the gene ubxn4 are located.  This part of the studied region is where 26_1414 is located
in the EUR tree and 32_1361 in the EAS tree.  All 14_57 samples express the series 55_180,
7_1303, and 4_1442 along with the upper part of 14_57 in this region.
</div>

In [2]:
HTML(dm.series_html(di_14_57))

In [3]:
plt_obj = dm.superset_yes_no([di_14_57], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_14_57.unique_snps_per_allele()
count_data

array([(0, 4941), (1, 1), (2, 1), (3, 1), (7, 3), (8, 2), (12, 2), (13, 2),
       (14, 55)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
an.sa_117_1685.unique_snps_per_allele(am_14_57)

array([(70, 1), (115, 2), (117, 54)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [6]:
an.sa_123_1561.unique_snps_per_allele(am_14_57)

array([(120, 1), (121, 4), (122, 52)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
aps_122, am_122 = an.sa_123_1561.snps_from_aps_value(122, am_14_57)
aps_122

array([52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
       52, 52,  0, 52])

In [8]:
an.sa_62_1265.unique_snps_per_allele(am_14_57)

array([(59, 1), (62, 56)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [9]:
an.sa_193_843.unique_snps_per_allele(am_14_57)

array([(185, 1), (191, 1), (192, 6), (193, 49)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [10]:
di_15_27 = 353459
plt_obj = dm.superset_yes_no([di_14_57], [di_15_27], min_match=0.001)
plt_obj.do_plot()
am_not_15_27 = plt_obj.plot_context.yes_allele_mask
HTML(plt_obj.get_html())

In [11]:
di_20_56 = 354133
plt_obj = dm.superset_yes_no([di_14_57, dm.di_7_90, di_20_56], [di_15_27], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [12]:
HTML(plt_obj.get_html())

In [13]:
plt_obj = dm.superset_yes_no([di_14_57, dm.di_7_90], [di_20_56, di_15_27], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [14]:
HTML(plt_obj.get_html())

In [15]:
plt_obj = dm.superset_yes_no([di_14_57, dm.di_7_90, dm.di_39_1014], [di_20_56, di_15_27], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [16]:
HTML(plt_obj.get_html())

In [17]:
plt_obj = dm.superset_yes_no([di_14_57, dm.di_7_90], [dm.di_39_1014, di_20_56, di_15_27], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [18]:
HTML(plt_obj.get_html())

In [19]:
plt_obj = dm.superset_yes_no([di_14_57], [dm.di_7_90], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
an.sa_117_1685.unique_snps_per_allele(am)

array([(70, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [22]:
an.sa_117_1685.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [23]:
an.sa_123_1561.unique_snps_per_allele(am)

array([(122, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [24]:
an.sa_123_1561.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1])

In [25]:
an.sa_62_1265.unique_snps_per_allele(am)

array([(59, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [26]:
an.sa_62_1265.alleles_per_snp(am)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
an.sa_193_843.unique_snps_per_allele(am)

array([(185, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [28]:
an.sa_193_843.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
sa_7_90.alleles_per_snp(am)

array([0, 0, 1, 1, 1, 1, 1])