In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
import genomes_dnj.lct_interval.series_masks as sm
output_notebook(hide_banner=True)
di_10_25 = 353386
sa_10_25 = snp_anal.series_anal_cls(di_10_25, sm.series_data)
am_10_25 = dm.allele_mask_from_index(di_10_25)
sa_5_1460 = snp_anal.series_anal_cls(dm.di_5_1460, sm.series_data)
sa_29_68 = snp_anal.series_anal_cls(dm.di_29_68, sm.series_data)

<h3>Series 10_25</h3>
<div style="width:700px">
<p>
This notebook documents the series 10_25 and its 10 SNPs.  The 1000 genomes data includes
4981 samples that express none of its 10 SNPs and 23 samples that express all 10 of them.
Another 2 samples express 9 of the SNPs. The 10 SNP series covers more than 457,000 DNA bases.
It is over expressed in South Asian populations.  It is not expressed by any samples from East
Asian or African populations.
<p>
The 25 samples include 17 that express the same complex association of 19 series across the
studied interval.  In the hierarchy formed by those associations 10_25 is a child of 29_68.
29_68 is a direct child of 193_843 without 6_713 or 4_815.
<p>
The other 8 samples show histories of a variety of genetic events.  4 samples have lost the
middle SNP of the series 5_1460.  2 samples have experienced recombination events in the
very top part of the studied region.  1 sample has lost the top 4 SNPs of 29_68 while retaining
all of the 193_843 SNPs.  The most likely explanation is a recombination event with a chromosome
that expressed the 193_843 hierarchy but not 29_68.
</div>

In [2]:
HTML(dm.series_html(di_10_25))

In [3]:
plt_obj = dm.superset_yes_no([dm.di_10_25], min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

In [4]:
count_data = sa_10_25.unique_snps_per_allele()
count_data

array([(0, 4981), (1, 2), (9, 2), (10, 23)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [5]:
di_5_1296 = 354129
plt_obj = dm.superset_yes_no([di_10_25, dm.di_193_843, dm.di_24_1504, dm.di_5_1460, di_5_1296], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [6]:
HTML(plt_obj.get_html())

In [7]:
di_5_1296 = 354129
plt_obj = dm.superset_yes_no([di_10_25, dm.di_193_843, dm.di_24_1504, dm.di_5_1460], [di_5_1296], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [8]:
HTML(plt_obj.get_html())

In [9]:
plt_obj = dm.superset_yes_no([di_10_25, dm.di_193_843, dm.di_24_1504, dm.di_29_68], [dm.di_5_1460], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [10]:
HTML(plt_obj.get_html())

In [11]:
sa_5_1460.alleles_per_snp(am)

array([3, 3, 0, 3, 3])

In [12]:
sa_5_1460.alleles_per_snp(am_10_25)

array([25, 25, 21, 25, 25])

In [13]:
plt_obj = dm.superset_yes_no([di_10_25, dm.di_193_843, dm.di_24_1504], [dm.di_29_68, dm.di_5_1460], min_match=0.5)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [14]:
HTML(plt_obj.get_html())

In [15]:
sa_29_68.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0])

In [16]:
sa_5_1460.alleles_per_snp(am)

array([1, 1, 0, 1, 1])

In [17]:
an.sa_193_843.alleles_per_snp(am)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
plt_obj = dm.superset_yes_no([di_10_25, dm.di_193_843], [dm.di_24_1504], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [19]:
HTML(plt_obj.get_html())

In [20]:
plt_obj = dm.superset_yes_no([di_10_25], [dm.di_193_843], min_match=0.001)
plt = plt_obj.do_plot()
am = plt_obj.plot_context.yes_allele_mask
show(plt)

In [21]:
HTML(plt_obj.get_html())

In [22]:
sa_10_25.alleles_per_snp(am)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
an.sa_117_1685.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [24]:
an.sa_123_1561.alleles_per_snp(am)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
an.sa_62_1265.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
an.sa_193_843.alleles_per_snp(am)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])