In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
import genomes_dnj.lct_interval_snp_anal.lct_interval_snp_anal as snp_anal
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)
di_9_39 = 353559
sa_9_39 = snp_anal.series_anal_cls(di_9_39, sm.series_data)
am_9_39 = dm.allele_mask_from_index(di_9_39)

<h3>Series 9_39</h3>
<div style="width:700px">
<p>
This notebook documents the series 9_39 and its 9 SNPs.  The 1000 genomes data includes
4959 samples that express none of its 9 SNPs and 35 samples that express all 9 of them.
Another 4 samples express 8 of the SNPs. The 9 SNP series covers almost 410,000 DNA bases.
It is overexpressed in European and American populations.  It is under expressed in
African, East Asian, and South Asian populations.
<p>
The series 9_39 is a child of 8_267 that does not express 193_843 or 123_1561.  Analysis
of series SNPs expressed by 9_39 samples shows that all 39 of them have lost top SNPs
from 117_1685, 123_1561, and 193_843.  6 top SNPs have been lost from 117_1685.
16 top SNPs have been lost from 123_1561.  23 top SNPs have been lost from 193_843.
<p>
These SNPs appear to have been lost through a recombination event with a chromosome
that expressed the series 32_1361 and 81_857 from the EAS tree root.  29 of the
9_39 samples express the association of series that resulted from the recombination.
The other 10 show histories of additional recombination events.
</div>

In [2]:
HTML(dm.series_html(di_9_39))

In [3]:
count_data = sa_9_39.unique_snps_per_allele()
count_data

array([(0, 4959), (1, 5), (2, 2), (7, 3), (8, 4), (9, 35)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [4]:
plt_obj = dm.superset_yes_no([di_9_39], min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [5]:
HTML(plt_obj.get_html())

In [6]:
count_data = an.sa_117_1685.unique_snps_per_allele(am_9_39)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [7]:
count_data

array([(110, 1), (111, 38)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [8]:
an.sa_117_1685.alleles_per_snp(am_9_39)

array([39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39,  0,  0,  0,  0,  0,  0])

In [9]:
count_data = an.sa_123_1561.unique_snps_per_allele(am_9_39)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [10]:
count_data

array([(106, 15), (107, 24)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [11]:
an.sa_123_1561.alleles_per_snp(am_9_39)

array([39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 36, 39, 39, 29, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 38, 39, 39, 39,
       39, 39, 39, 39, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0])

In [12]:
count_data = an.sa_62_1265.unique_snps_per_allele(am_9_39)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [13]:
count_data

array([(61, 1), (62, 38)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [14]:
count_data = an.sa_193_843.unique_snps_per_allele(am_9_39)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [15]:
count_data

array([(169, 1), (170, 38)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [16]:
an.sa_193_843.alleles_per_snp(am_9_39)

array([39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [17]:
plt_obj = dm.superset_yes_no([di_9_39, dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [18]:
HTML(plt_obj.get_html())

In [19]:
plt_obj = dm.superset_yes_no([di_9_39, dm.di_9_1170], [dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [20]:
HTML(plt_obj.get_html())

In [21]:
plt_obj = dm.superset_yes_no([di_9_39, dm.di_4_1442], [dm.di_9_1170, dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [22]:
HTML(plt_obj.get_html())

In [23]:
plt_obj = dm.superset_yes_no([di_9_39], [dm.di_4_1442, dm.di_9_1170, dm.di_81_857], min_match=0.001)
plt = plt_obj.do_plot()
show(plt)

In [24]:
HTML(plt_obj.get_html())